### ISSUE TITLE
Tags and Categories strange behaviour..

### ISSUE THREAD

**Issue by aaronfromminivegas** [daylightstudio/FUEL-CMS#296]
Hi!

I'm having a weird issue with tags and categories. What I'm hoping to do is have 4 categories of tags where I can assign multiple tags to multiple restaurants. Restaurants is a custom model which is:

```
<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');
 
require_once(FUEL_PATH.'models/base_module_model.php');
 
class Restaurants_model extends Base_module_model {

	public $has_many = array('tags' => array(FUEL_FOLDER => 'fuel_tags_model'));
 
    function __construct()
    {
        parent::__construct('restaurants');
    }
}
 
class Restaurant_model extends Base_module_record {
 
}
```

This is my tag tree:

![screen shot 2015-01-07 at 17 33 59](https://cloud.githubusercontent.com/assets/10085359/5649052/69ff1120-9693-11e4-96c1-eaa8ddd62fc1.png)

And this is where it starts to go wrong. This is what appears on a custom model page:

![screen shot 2015-01-07 at 17 34 32](https://cloud.githubusercontent.com/assets/10085359/5649064/7bb962c6-9693-11e4-86d1-aa9c62eac982.png)

This is what happens when I try and edit the 'Neighbourhood' tag.

![screen shot 2015-01-07 at 17 36 34](https://cloud.githubusercontent.com/assets/10085359/5649106/beb5fa3a-9693-11e4-98a2-757b847dabdc.png)

And if I add a tag without a category, it appears on the Restaurant edit page like so:

![screen shot 2015-01-07 at 17 39 41](https://cloud.githubusercontent.com/assets/10085359/5649185/3786d358-9694-11e4-8d94-ac3cfd3bb2bb.png)

(notice the small little gap above Cuisine).

When I select this row and edit it, this appears:

![screen shot 2015-01-07 at 17 39 53](https://cloud.githubusercontent.com/assets/10085359/5649193/4333d872-9694-11e4-9184-171789caca85.png)

I've installed Fuel CMS today and running PHP 5.5.14. This error appears across all browsers.

Could someone help clarify?

Best,

**Comment by daylightstudio** [comment]
This issue has been fixed in the development branch. The options_list method on fuel_tags_model was using the categories name instead of the tags name:
https://github.com/daylightstudio/FUEL-CMS/blob/develop/fuel/modules/fuel/models/fuel_tags_model.php

**Comment by aaronfromminivegas** [comment]
Oh great, thanks!

Best,
