### ISSUE TITLE
A PHP Error was encountered Severity: Notice Message: Only variable references should be returned by reference Filename: core/Common.php Line Number: 257

### ISSUE THREAD

**Issue by jpswade** [daylightstudio/FUEL-CMS#300]
There's a bug with FuelCMS 1.2.1 on PHP 5.6...

```
A PHP Error was encountered
Severity: Notice
Message: Only variable references should be returned by reference
Filename: core/Common.php
Line Number: 257
```

Screenshot: http://i.imgur.com/rDFblff.png

Solution 1:
```
"fuel\codeigniter\core\Common.php"
<return $_config[0] =& $config;
>$_config[0] =& $config;
>return $_config[0]; 
```

Solution 2:
* Update CodeIgniter from 2.2.0 to 2.2.1.
* https://github.com/bcit-ci/CodeIgniter

**Comment by jpswade** [comment]
Your fix solves it for me.

**Comment by spidey123** [comment]
it works. thanks!

**Comment by aportac** [comment]
thanks!

**Comment by sancoLgates** [comment]
it works, thank you for your help

**Comment by pradita033** [comment]
it works for me.. :dancer:

**Comment by rpalzona** [comment]
it worked!!!!! thank you!

**Comment by julioware** [comment]
very good !!! thank you!

**Comment by blupalmail** [comment]
File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/views/includes/header_v.php


A PHP Error was encountered

Severity: Notice

Message: Undefined variable: metakeywords

Filename: includes/header_v.php

Line Number: 11

Backtrace:

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/views/includes/header_v.php
Line: 11
Function: _error_handler

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/controllers/Blupal.php
Line: 884
Function: view

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/index.php
Line: 292
Function: require_once

" />
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: metadescription

Filename: includes/header_v.php

Line Number: 12

Backtrace:

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/views/includes/header_v.php
Line: 12
Function: _error_handler

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/controllers/Blupal.php
Line: 884
Function: view

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/index.php
Line: 292
Function: require_once

" />
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: ogdescription

Filename: includes/header_v.php

Line Number: 46

Backtrace:

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/views/includes/header_v.php
Line: 46
Function: _error_handler

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/controllers/Blupal.php
Line: 884
Function: view

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/index.php
Line: 292
Function: require_once

">
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: ogtitle

Filename: includes/header_v.php

Line Number: 48

Backtrace:

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/views/includes/header_v.php
Line: 48
Function: _error_handler

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/controllers/Blupal.php
Line: 884
Function: view

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/index.php
Line: 292
Function: require_once

">
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: ogurl

Filename: includes/header_v.php

Line Number: 51

Backtrace:

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/views/includes/header_v.php
Line: 51
Function: _error_handler

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/controllers/Blupal.php
Line: 884
Function: view

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/index.php
Line: 292
Function: require_once

">
Go Home
Track Your Complaint  
Enter Complaint Number
 
Book mineral water online
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: H1

Filename: views/brandlists.php

Line Number: 19

Backtrace:

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/views/brandlists.php
Line: 19
Function: _error_handler

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/controllers/Blupal.php
Line: 885
Function: view

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/index.php
Line: 292
Function: require_once


A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
Click for Pricing & Details 
Aqua Fresh
Click for Pricing & Details 
TAJA
Click for Pricing & Details 
SURYA
 
LOGIN | HOME | JOIN US | CONTACT US | FAQ | TERMS OF USER | PRIVACY & LEGAL POLICY | BOTTLED WATER COMPLAINT | SITEMAP | BRANDS
COPYRIGHT © BLUPAL. ALL RIGHTS RESERVED. BACK TO TOP

**Comment by naufu7** [comment]
Thanks a lot :100: 

Working fine now :)
