### ISSUE TITLE
Call to undefined function fuel_nav()

### ISSUE THREAD

**Issue by satishjunghare** [daylightstudio/FUEL-CMS#301]
Hi friends. I am new in fuel cms, and trying to create new controller called "hello" and pasted this code.
<?php
class Hello extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
    }
    public function index()
    {
        // load the fuel_page library class and pass
        // it the view file you want to load
		$this->load->module_library(
            FUEL_FOLDER,
            'fuel_page',
            array('location' => 'hello')
        );
        $this->fuel_page->render();
    }
}
So now when I call hello page from url "http://localhost/fuel/hello" then it shows me this error.
"Unable to load the requested class: fuel_page"
can anyone tell me why this comming.
thank you. :)

**Comment by daylightstudio** [comment]
That appears to be an older code example. Try the following:
```
$vars = array(); // an array of variables to pass to the page
$this->fuel->pages->render('hello', $vars);
```
