### ISSUE TITLE
Character encoding issue in form input

### ISSUE THREAD

**Issue by SunYunSoft** [daylightstudio/FUEL-CMS#303]
Hi

When use a simple module in the admin panel, we have some input in the textview, however, some character like "“", "”" is converted to `&ldquo;` and `&rdquo;`  and save to database.

1) I have tried to print the $values in on_before_save(), and indeed &ldquo; is sent to the PHP backend. 
2) I also tried to set all the possible config to charset format to UTF-8, but still could not fix issue.

Could you please help give some possible hint on this? Thanks in advance.

**Comment by daylightstudio** [comment]
There is a property of "auto_encode_entities" that can be set on your model as either TRUE, FALSE or an array of field names to apply the entity encoding. By default it is set to TRUE.

**Comment by SunYunSoft** [comment]
Thanks very much, this solves my issue.
