### ISSUE TITLE
not load admin panel

### ISSUE THREAD

**Issue by AhrimanSefid** [daylightstudio/FUEL-CMS#304]
Hi All.
me install in local but not load admin panel.
To access the FUEL admin, go to:
http://localhost/FU/fuel
User name: admin
Password: admin (you can and should change this password and admin user information after logging in)
win 8.1 wamp
http://localhost/FU/fuel/start

**Comment by daylightstudio** [comment]
Did you enable the admin in the fuel/application/config/MY_fuel.php file?

**Comment by AhrimanSefid** [comment]
how to edit?
// path to the fuel admin from the web base directory... MUST HAVE TRAILING SLASH!
$config['fuel_path'] = 'fuel/';

**Comment by daylightstudio** [comment]
`$config['admin_enabled'] = TRUE;`

**Comment by vc7deo** [comment]
I have also the same problem.I did all the above settings
http://127.0.0.1/fuel/fuel/start
![image](https://cloud.githubusercontent.com/assets/8149102/7956978/aed6105a-0a01-11e5-8c84-eb7e5375deb3.png)

**Comment by daylightstudio** [comment]
What value do you have set in your .htaccess for the RewriteBase?

**Comment by vc7deo** [comment]
i added "fuel"
Options +FollowSymLinks

<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /fuel/

	<Files .*>
		Order Deny,Allow
		Deny From All
	</Files>

	# Allow asset folders through
	RewriteRule ^(fuel/modules/(.+)?/assets/(.+)) - [L]

	# Protect application and system files from being viewed
	RewriteRule ^(fuel/install/.+|fuel/crons/.+|fuel/data_backup/.+|fuel/codeigniter/.+|fuel/modules/.+|fuel/application/.+) - [F,L]


	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d

	RewriteRule .* index.php/$0 [L]
	
	# Prevents access to dot files (.git, .htaccess) - security.
	RewriteCond %{SCRIPT_FILENAME} -d
	RewriteCond %{SCRIPT_FILENAME} -f
	RewriteRule "(^|/)\." - [F]
	
</IfModule>
Options -Indexes

**Comment by daylightstudio** [comment]
In your case, FUEL appears to be setup at the root of your webserver and you don't need the:
```
RewriteBase /fuel/
```
Just
```
RewriteBase /
```

**Comment by vc7deo** [comment]
i tried it first.then i added "fuel"  :(

**Comment by daylightstudio** [comment]
Does this URL work for you (without RewriteBase / in the .htaccess)?
```
http://127.0.0.1/fuel/login
```

**Comment by vc7deo** [comment]
there is no sign of hope

![image](https://cloud.githubusercontent.com/assets/8149102/7980056/03d745d6-0ac2-11e5-9bee-6f499b0619b1.png)

**Comment by vc7deo** [comment]
I enabled everything.please check if i miss anything there.

![screen shot 2015-06-04 at 14 01 44](https://cloud.githubusercontent.com/assets/8149102/7980103/5a5f4d54-0ac2-11e5-875a-e90423e367a8.png)

**Comment by daylightstudio** [comment]
So it looks like I may have been wrong and that you installed fuel in a subfolder of your server called "fuel" correct? If so, then you will need the RewriteBase /fuel/ set. Are you sure you have mod_rewrite and .htaccess enabled for your server?
