### ISSUE TITLE
Custom field value setting

### ISSUE THREAD

**Issue by SunYunSoft** [daylightstudio/FUEL-CMS#305]
Hi

I have use a custom field with custom js, css and it functions correctly itself. However, when submit the form, we could not see custom field value sent to server. 
I think it would related to our own setting for the HTML, JS, etc. Would you please help guide us how to make the simple module receive the custom field value? So we could change our js to set the value correctly.

**Comment by daylightstudio** [comment]
I'll need some code examples to be able to help.

**Comment by SunYunSoft** [comment]
in the model form_field(), we set the custom filed
                $data['readers'] = array (
                                        'type' => 'user_list_field',
                );
in the config file, we set the 
$fields ['user_list_field'] = array (
                'class' => array (
                                APPPATH . 'libraries' => 'MY_custom_fields'
                ),
                'function' => 'user_list_fields',
                'js' => array (
                                'my_js'
                )
);

in the MY_custom_fields, 
        public function user_list_fields($params) {
                $form_builder = & $params ['instance'];

                return '<div class="Background left">
                <ul id="dept_user" class="ztree"></ul>
        </div>';
        }

in the js file, we have something like selected_dept and selected to save data.
function postSelectedData (model, key) {
.....

        xmlhttp.send("dept="+selected_dept.toString()+"&user="+selected.toString() + "&seq="+seq + "&model="+model);
}

**Comment by daylightstudio** [comment]
Is there anything calling "postSelectedData"? Or did you specify the 'js_func' parameter in the $fields ['user_list_field'] configuraiton? Does that javascript function get called at all?

**Comment by SunYunSoft** [comment]
1) postSelectedData is not called right now, we write this to do testing and verify the custom field data is correct.
2) we don't specify the js function, and we don't know how to let the form know how to the fuel CMS form builder knows the value of the custom field

**Comment by daylightstudio** [comment]
Have you seen this area in the docs about the custom field configuration parameters?
http://docs.getfuelcms.com/general/forms#association_parameters
The js_function parameter should be the name of a javascript function to execute upon loading your form field. This is only needed if your js file doesn't automatically look for fields and execute. Normally the form field has a class associated with it which allows you to target it with javascript. If you look at the fuel/modules/fuel/assets/js/fuel/custom_fields.js file, it lists a bunch of functions that the built in custom form fields use. Note for example that the "fuel.fields.datetime_field" targets elements with a class of ".datepicker" to execute its javascript.
