### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by kevinfelisilda** [daylightstudio/FUEL-CMS#306]
I had this following lines in my view file and seems to cause some error during compile process.

```php
<video id="ribbit-slash-video" class="video-js vjs-default-skin"
	controls preload="auto"
	poster="<?php echo img_path('rvideo-holder.png') ?>"
	data-setup='{"example_option":true}'>
		<source src="<?php echo media_path('splash-video.mp4') ?>" type='video/mp4' />
		<p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
</video>
```
this string actually causes the error
```
data-setup='{"example_option":true}'
```
I think it is the problem with Dwoo Template Engine.

Is there anyway we can retain that kind of json format in the view file without getting conflict with template engine?

Thanks,

**Comment by daylightstudio** [comment]
If you add a space after the "{ " it won't detect it. Also, there is a {literal} and {/literal} template tag you can surround that area with to prevent it from trying to compile that area.
