### ISSUE TITLE
Fuel-CMS Admin Login Issue #247 #304 checked

### ISSUE THREAD

**Issue by trysten** [daylightstudio/FUEL-CMS#308]
After much search, I've come to you. After following all of the instructions for installation, I get no response([only headers](http://paste.debian.net/162507/)) at the url <code>http://localhost/index.php/fuel/login/5a6e566c62413d3d</code>

Apache 2.2.22 (Debian)
PHP 5.4.38-0

I added the following line to /etc/apache2/sites-available/default to get php to work
<code>Action application/x-httpd-php /cgi-bin/php5</code>
other than that, nothing else has been changed.

Any ideas? could it have something to do with the database configuration? I don't know how to test it.

**Comment by daylightstudio** [comment]
Is there anything showing up in your Apache logs?

**Comment by trysten** [comment]
i haven't been able to get php to spit out any errors or generate any error logs. /var/log/apache2/error.log doesn't have anything relevant.

**Comment by daylightstudio** [comment]
Are you able to get any PHP to work on that server?

**Comment by trysten** [comment]
PHP does indeed work. other pages that use include() are working (and break when i a2dismod php). the starter fuel-cms instruction page is also working fine. thank you for working with me, i've been trying to increase my skills in the past few days so i could understand this issue. i think i understand cgi vs module so far, but i just can't get apache to tell me anything about what is going on.

what configuration should i use to get debug messages from php? i'm using the php.ini-development from my distribution.

**Comment by daylightstudio** [comment]
To confirm, the response is just a blank page (not a 404 error message... if that was the case, I would tell you to make sure that $config['admin_enabled'] = TRUE; is set in the fuel/application/config/MY_fuel.php file). Have you made any other changes to the config files and if so, is it valid PHP syntax (not missing any ending semicolons, etc)? Sometimes, PHP syntax errors in the config files will make the page be blank.

**Comment by trysten** [comment]
yes, it's a blank page. beyond that, it's a generated URL that had to have come about because of some php running. i have started with a fresh copy of fuel several times with the same problem. after double-checking my config files i cannot find anything aberrant.

**Comment by tlagard** [comment]
Possible issue with the htaccess file or lack there of?  I believe that I have ran into this issue before and something with the file was the issue.

**Comment by daylightstudio** [comment]
You may also want to try putting debug statements (e.g. exit('still here'); ) in the index.php file then if you get through that, the fuel/codigniter/core/CodeIgniter.php file to see where it may be causing the errors.

**Comment by trysten** [comment]
Thank you. I've found it's messing up when loading the security class. I do not know how to generate error logs, though error logging is mentioned in CodeIgniter.php I have not been able to figure it out. 

yes, I think there's something about the debian configuration of apache that may be messing the the .htaccess files that ship with fuel. but i think my problem is separate

**Comment by trysten** [comment]
Problem persists after renaming .htaccess and configuring config.php properly. 

I was able to get fuel running on my hosting service without any problems, however I still cannot get the admin panel to show up on development server. I have specified logfiles in php.ini but they do not exist or I cannot find them.

**Comment by trysten** [comment]
Got Xdebug working with Vdebug(vim plugin)

As soon as I 'Step Into' line 308, the debugger is just.. done, at least when $class = login. When $class = admin it goes through just fine.

It's maddening to get a debugger working and not really get any information from it. First time I've debugged PHP, anyways.

**Comment by trysten** [comment]
Progress!! The problem is definitely [with the mysql driver](https://github.com/daylightstudio/FUEL-CMS/blob/master/fuel/codeigniter/database/drivers/mysql/mysql_driver.php#L91). My debugger stops after stepping into line 91.

**Comment by daylightstudio** [comment]
If you remove the @ in front of mysql_pconnect, does it report any errors?

**Comment by trysten** [comment]
yes, a fatal call to undefined function.

**Comment by trysten** [comment]
Successed! changing $db['default']['pconnect'] to FALSE worked! I presume it's not using the same mysqll_pconnect... wait a second... why does my code say mysqll?!? There's no way I could have made that change! I'm downloading a new clone now. thanks for all the help!!

**Comment by trysten** [comment]
TIL the @ silences error output.
