### ISSUE TITLE
'Welcome' page scrolled to the bottom

### ISSUE THREAD

**Issue by olimortimer** [daylightstudio/FUEL-CMS#309]
Just downloaded FUEL CMS and browsed to the index.php file.  The page that showed was titled 'What's Next?' and didn't have any install instructions.  I thought that was a bit odd, until I suddenly realised that the page had automatically scrolled to the bottom, so all the install instructions were at the top of the page.

This is on Chrome 41.0.2272.89 (64-bit) on Mac OS X 10.10.2.

**Comment by daylightstudio** [comment]
Thanks for the report. This looks to be the issue:
https://code.google.com/p/chromium/issues/detail?id=452854
Will work on a fix.

**Comment by jpswade** [comment]
One solution would be to use something like font awesome instead of the svg...

**Comment by daylightstudio** [comment]
Looks like just changing it from an object tag to an image tag did the trick:
https://github.com/daylightstudio/FUEL-CMS/commit/a4d099c6c99c544f1a2de6fe80fe65cc07a69720
