### ISSUE TITLE
The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead

### ISSUE THREAD

**Issue by jpswade** [daylightstudio/FUEL-CMS#310]
In unique circumstances where the [criteria for mysql_real_escape_string()](https://github.com/daylightstudio/FUEL-CMS/blob/master/fuel/codeigniter/database/drivers/mysql/mysql_driver.php#L313) is not met you will get this error:

```
A PHP Error was encountered
Severity: 8192

Message: mysql_escape_string(): This function is deprecated; use mysql_real_escape_string() instead.

Filename: mysql/mysql_driver.php

Line Number: 320
```

For example, if a link to the server could not be established.

A workaround is to silence the error:
$str = @mysql_escape_string($str);

However, since mysql_real_escape_string() is also deprecated, it may be worth exploring better options such as PDO::quote() or mysqli_real_escape_string().

**Comment by daylightstudio** [comment]
Good to know. I'm curious how you were using it where it didn't have a db connection set though.

**Comment by jpswade** [comment]
I only managed to reach this when toying around with Wordpress integration.

**Comment by jpswade** [comment]
Similarly:

```ERROR - 2015-04-09 19:59:49 --> Severity: 8192  --> mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead .../fuel/codeigniter/database/drivers/mysql/mysql_driver.php 91```

The solution here is to migrate to the mysqli or PDO CodeIgniter database driver.

**Comment by daylightstudio** [comment]
Does this error go away if you switch from mysql to mysqli in the database config for the drivier?

**Comment by jpswade** [comment]
In theory [yes](https://github.com/bcit-ci/CodeIgniter/issues/3445#issuecomment-70624079), however Fuel CMS just throws up a blank page when you change `$db['default']['dbdriver'] = 'mysql';` to `$db['default']['dbdriver'] = 'mysqli';`.

Though I've read it's not been tested with any other database.

No errors are logged either, debug gets to:
```DEBUG - 2015-04-09 22:22:36 --> Database Driver Class Initialized```

I see that as of [v1.2 there was a Database Update](http://www.getfuelcms.com/blog/2014/08/26/fuel-cms-1-2-released) that should allow it work.

**Comment by daylightstudio** [comment]
Yes... that was my next question as to what version you are running. Let me know if the latest version does the trick.

**Comment by jpswade** [comment]
Latest, based on the current master branch.

**Comment by daylightstudio** [comment]
Is there a specific page that it's erroring on (e.g. is it in the front end, back end or anywhere)? I would start to debug the fuel/codeigniter/database/drivers/mysqli/mysqli_driver.php to make sure the db_connect is working first (note that it suppresses errors with @ on several of the method calls).

Also, there have been a few updates regarding this issue in the develop branch, however, the mysqli support should be working in FUEL 1.2.

**Comment by jpswade** [comment]
I had to disable the production environment in order to get the error.

```Fatal error: Call to undefined function mysqli_connect()```

Using error suppression is really bad practice and much slower.

It seems absolutely pointless to use the inline error control operator and they should all be removed.

**Comment by daylightstudio** [comment]
You are right. CodeIgniter 3.0 has removed those error suppressions it appears but FUEL hasn't made that update yet.

**Comment by jpswade** [comment]
It seems to me there are two solutions:

- Depreciate the mysql_ dependency, use mysqli or PDO instead by default
- Remove error suppression

It's probably a good idea to add these to a ROADMAP and close this issue.
