### ISSUE TITLE
upload file however file name un-readable

### ISSUE THREAD

**Issue by SunYunSoft** [daylightstudio/FUEL-CMS#311]
Hi

When upload file and file name with only English character, it works fine. However, when uploading file with some double encoded character, the file name is missing. Mainly because it could not recognize the file name, so it just add a numeric for the file name.

I could successful upload file with utf8 encoding characters with the original CI upload helper. And even with fuel CMS, the CI upload data could also recognize the original file name.

**Comment by SunYunSoft** [comment]
After some check, it is found that in the controller module.php, _process_uploads, pathinfo() is used while it could not support all utf8 chars. So the name became blank.

**Comment by SunYunSoft** [comment]
more ever, after replacing the path info issue, i have found that, the file name handling with url_title also lead to blank file name, mainly because this regular expression '[^a-z0-9 _-]'          => '', is this really needed?

                $trans = array(
                        '&.+?;'                 => '',
                        '[^a-z0-9 _-]'          => '',
                        '\s+'                   => $separator,
                        '('.$q_separator.')+'   => $separator
                );

**Comment by daylightstudio** [comment]
The develop branch has already removed the use of url_title and will be in the next release. It appears that there is indeed a problem with support for certain characters and found a few workarounds:
http://stackoverflow.com/questions/4451664/make-php-pathinfo-return-the-correct-filename-if-the-filename-is-utf-8

**Comment by SunYunSoft** [comment]
Thanks for update. I have use custom path info to replace the path info function and comment out '[^a-z0-9 _-]' => '' for url_title, right now it is working fine.
