### ISSUE TITLE
Field datetime not save minutes of hour between 0:00 and 0:59

### ISSUE THREAD

**Issue by EveraldoReis** [daylightstudio/FUEL-CMS#312]
Field datetime set minutes as 00 after save when set time between 0:00 and 0:59. I'm not find the problem in fuel.

**Comment by daylightstudio** [comment]
Thanks for the report. A fix for this issue has been posted in the develop branch for the next release.
https://github.com/daylightstudio/FUEL-CMS/commit/26b4b149170ab51386b87f3ed98f8151f0728f39

**Comment by EveraldoReis** [comment]
Thanks, I'm using FuelCMS for many projects and this bug was frustrating me, but works fine now.
