### ISSUE TITLE
Tags html com atributos não salvam

### ISSUE THREAD

**Issue by EveraldoReis** [daylightstudio/FUEL-CMS#313]
If I try save content below the tag attributes will removed from code:

&lt;p style="line-height: 22.3999996185303px;"&gt;Lorem ipsum dolor sit amet, scripta singulis eu sit, ad dico partem scribentur sea, ea affert alienum eum. Ea legimus molestie antiopam sit, pro no falli adipisci, duo volumus oportere cu. Cum indoctum praesent reprehendunt eu, quas debitis denique vel id, audire aliquip scribentur ex mei. Ut alia blandit dissentias eam, ea nec ludus minimum principes.&lt;/p&gt;

And If I try save this content whole the code is removed:

&lt;p style="line-height: 22.3999996185303px;"&gt;Lorem ipsum dolor sit amet, scripta singulis eu sit, ad dico partem scribentur sea, ea affert alienum eum. Ea legimus molestie antiopam sit, pro no falli adipisci, duo volumus oportere cu. Cum indoctum praesent reprehendunt eu, quas debitis denique vel id, audire aliquip scribentur ex mei. Ut alia blandit dissentias eam, ea nec ludus minimum principes.&lt;/p&gt;

&lt;p style="line-height: 22.3999996185303px;"&gt;Lorem ipsum dolor sit amet, scripta singulis eu sit, ad dico partem scribentur sea, ea affert alienum eum. Ea legimus molestie antiopam sit, pro no falli adipisci, duo volumus oportere cu. Cum indoctum praesent reprehendunt eu, quas debitis denique vel id, audire aliquip scribentur ex mei. Ut alia blandit dissentias eam, ea nec ludus minimum principes.&lt;/p&gt;

&lt;p style="line-height: 22.3999996185303px;"&gt;Lorem ipsum dolor sit amet, scripta singulis eu sit, ad dico partem scribentur sea, ea affert alienum eum. Ea legimus molestie antiopam sit, pro no falli adipisci, duo volumus oportere cu. Cum indoctum praesent reprehendunt eu, quas debitis denique vel id, audire aliquip scribentur ex mei. Ut alia blandit dissentias eam, ea nec ludus minimum principes.&lt;/p&gt;

&lt;p style="line-height: 22.3999996185303px;"&gt;Lorem ipsum dolor sit amet, scripta singulis eu sit, ad dico partem scribentur sea, ea affert alienum eum. Ea legimus molestie antiopam sit, pro no falli adipisci, duo volumus oportere cu. Cum indoctum praesent reprehendunt eu, quas debitis denique vel id, audire aliquip scribentur ex mei. Ut alia blandit dissentias eam, ea nec ludus minimum principes.&lt;/p&gt;

&lt;p style="line-height: 22.3999996185303px;"&gt;Lorem ipsum dolor sit amet, scripta singulis eu sit, ad dico partem scribentur sea, ea affert alienum eum. Ea legimus molestie antiopam sit, pro no falli adipisci, duo volumus oportere cu. Cum indoctum praesent reprehendunt eu, quas debitis denique vel id, audire aliquip scribentur ex mei. Ut alia blandit dissentias eam, ea nec ludus minimum principes.&lt;/p&gt;

I changed many editor configs of trying for solve this but no success.

Help me please?

**Comment by daylightstudio** [comment]
If you are using CKEditor, inline styles may be causing that issue because they get stripped out.

**Comment by EveraldoReis** [comment]
I tested the markItUp, ckeditor and TinyMCE. Everyone has the same problem, I think the problem is to save.

**Comment by EveraldoReis** [comment]
I found the solution, was just enough to extend the class and override the Security _remove_evil_attributes () method. Simply just create MY_Security class in application/core.

**Comment by daylightstudio** [comment]
Actually, I think there may be an easier solution and I wouldn't recommend disabling that in the Security class. If this is happening in a module, there are various "sanitize_input" options you can specify for the module the fuel configuration option of "module_sanitize_funcs" has them (fuel/modules/fuel/config/fuel.php). The default (which is TRUE and includes all listed in the config) will include the xss_clean function which is what appears to be causing the issue for you. To fix this issue for your module, add the following to your modules configuration in fuel/applications/config/MY_fuel_modules.php to specify just the sanitation functions you want:
```
...
'sanitize_input' => array('template','php'),
...
```
