### ISSUE TITLE
URL encoded entities save to DB as their decoded counterparts 

### ISSUE THREAD

**Issue by digsite** [daylightstudio/FUEL-CMS#315]
I have a simple module, in which, I have a url type field, that a user can paste in a Google Maps URL for their location. The Google Map URL that is being entered is URL encoded. After saving, however, the database value and the display value in the field are no longer URL encoded. 

__Example__
Original Google Map URL
```
https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2918.4298423575547!2d-71.46386619999997!3d42.9902827!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e24f264963a1bd%3A0x4832c7a2ffdef1ea!2s20+Market+St+%231000%2C+Manchester%2C+NH+03101!5e0!3m2!1sen!2sus!4v1429631205160
```
After Save
```
https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2918.4298423575547!2d-71.46386619999997!3d42.9902827!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e24f264963a1bd:0x4832c7a2ffdef1ea!2s20+Market+St+#1000,+Manchester,+NH+03101!5e0!3m2!1
```

This happens regardless of the model's $auto_encode_entities is set to FALSE. The field itself has the following settings in the form_fields() function:
```php
$fields['google_map']['type'] = 'url';
$fields['google_map']['ignore_representative'] = TRUE;
```

I'm not sure why the value is being decoded and saved as such. Any help would be greatly appreciated.

**Comment by daylightstudio** [comment]
It may be the xss_clean function that is doing this. I would try adding the following to your module configuration in your MY_fuel_modules.php file:
```
'sanitize_input' => array('template','php'),
```

**Comment by digsite** [comment]
Thank you for the quick response! That solution worked splendidly. 

I have one more question for my own future reference. If I'm correct in assuming that this solution removes XSS filtering across all fields in the module, is there a way to adjust the sanitization options at a field level?

**Comment by daylightstudio** [comment]
There is. On the model, there are a few sanitization properties that can be modified to effect only certain fields:
```
public $auto_trim = TRUE;
public $auto_encode_entities = TRUE;
public $xss_clean = TRUE;
```
By default they are boolean values and note that xss_clean is set to FALSE. However, they can be changed to an array that specifies the field names to apply it to.

**Comment by digsite** [comment]
Excellent! Thank you again. :) Closing the issue.
