### ISSUE TITLE
Cannot upload .csv files to docs assets directory out of the box

### ISSUE THREAD

**Issue by jpswade** [daylightstudio/FUEL-CMS#316]
As per the image trying to upload a file called 'any.csv' results in an error saying:

* "You cannot select a .csv file".

![capture](https://cloud.githubusercontent.com/assets/1087963/7431687/01958daa-f019-11e4-9559-8b7256b8cf11.PNG)

**Comment by daylightstudio** [comment]
The general asset folder is restricted on the different file types that can be uploaded. To change this, add the following to your MY_fuel.php file:
```
$config['editable_asset_filetypes']['assets'] = 'csv|jpg|jpeg|jpe|png|gif|mov|mpeg|mp3|wav|aiff|pdf|css|zip|svg';
```

**Comment by jpswade** [comment]
I think that it's an "out of the box" problem that "docs" such as .csv, .doc, .xls, etc aren't handled as a separate asset.

As in, I would expect these file types to be handled "out of the box" without having to add anything.

Cheers.

**Comment by daylightstudio** [comment]
Those aren't typically files that need to be managed in a CMS when building websites so that is why they aren't included by default.

**Comment by jpswade** [comment]
You have a mime type for it, but you need to add the following:

'text/plain', 'text/html'

**Comment by jpswade** [comment]
If you're happy to support document assets such as pdf, I see no reason not to adding support for csv.

**Comment by daylightstudio** [comment]
It does support CSV... you just need to add it to the configuration. There are a lot of configuration values that may need to change between projects. This is just one of them.
