### ISSUE TITLE
base_module_model::_editable_by_user

### ISSUE THREAD

**Issue by croaker000** [daylightstudio/FUEL-CMS#318]
When used with $limit_to_user_field to restrict users to their own pages. 

When a new user creates their first page the page is created but displays an "no permissions" error along with a PHP error.

A new user will have $rec = null so we should check if empty($rec) before checking permissions.

Proposed fix:

    protected function _editable_by_user()
    {
       if (!empty($this->limit_to_user_field) AND !$this->fuel->auth->is_super_admin())
       {
          $rec = $this->find_one_array($this->_tables['fuel_users'].'.id = '.$this->limit_to_user_field);
          if ((!empty($rec)) &&($rec[$this->limit_to_user_field] != $this->fuel->auth->user_data('id')))
          {
             $this->add_error(lang('error_no_permissions'));
             return FALSE;
          }
       }
       return TRUE;
    }

**Comment by daylightstudio** [comment]
Good catch... and thanks for the proposed fix. Will implement for the upcoming release.
