### ISSUE TITLE
Blog does not work with mysqli database driver

### ISSUE THREAD

**Issue by jpswade** [daylightstudio/FUEL-CMS#320]
To reproduce:
1. Setup Fuel CMS
2. Enable Blog
3. Change driver to mysqli

Blank page is displayed (no errors).

My guess is that MY_Model.php depends on MY_DB_mysql_result:

https://github.com/daylightstudio/FUEL-CMS/blob/master/fuel/modules/fuel/core/MY_Model.php#L458

A ternary check may needed to be added to resolve this.

**Comment by daylightstudio** [comment]
Thanks for the report... does this fix the issue for you if added in MY_Model? 
```
if (empty($query)) $query = ($this->db->dbdriver == 'mysql') ? new MY_DB_mysql_result() : new MY_DB_mysqli_result();
```

**Comment by jpswade** [comment]
I don't think MY_DB_mysqli_result exists.
