### ISSUE TITLE
Custom Dwoo plugins not bound

### ISSUE THREAD

**Issue by airways** [daylightstudio/FUEL-CMS#321]
We created a custom Dwoo plugin under applications/dwoo/plugins and it was not available, giving this error:

```
Plugin partial can not be found, maybe you forgot to bind it if it's a custom plugin ?
```
We fixed this by modifying MY_Parser.php within the spawn() method to add a directory:

```
$dwoo = new Dwoo;
$dwoo->getLoader()->addDirectory(ARION_ROOT.'libraries/dwoo/plugins');
```

It would be great if it were possible for all advanced module directories to be added at this point as well as we have so far kept everything within a single advanced module directory and would like to continue to do so.

p.s. I tried to post this on your forum but the post won't go live -- confirming my email address appears to not have worked properly, it always says "You need to confirm your email address. Click here to resend the confirmation email."

**Comment by daylightstudio** [comment]
There have been some updates to the Parsing engine in the develop branch which will be in the next release (such as support for Twig). You access it on the CodeIgniter master object like so: 
$CI =& get_instance();
$CI->fuel->parser->engine->getLoader()->addDirectory(ARION_ROOT.'libraries/dwoo/plugins'); You can set this code perhaps to a CI hook:
https://ellislab.com/codeigniter/user-guide/general/hooks.html

That's strange about the forum. I actually see your post here:
http://forum.getfuelcms.com/discussion/2097/custom-dwoo-plugins-not-bound
