### ISSUE TITLE
Duplicate content due to trailing slashes

### ISSUE THREAD

**Issue by jpswade** [daylightstudio/FUEL-CMS#322]
Confusingly Fuel CMS delivers duplicate content for every page you create.

You can access this by adding a trailing slash.

For example:

* http://www.getfuelcms.com/features
* http://www.getfuelcms.com/features/

See:

* http://googlewebmastercentral.blogspot.co.uk/2010/04/to-slash-or-not-to-slash.html

**Comment by daylightstudio** [comment]
This is something that can be handled with .htaccess. FUEL has a couple things in the admin that are  problematic with this so you can ignore those areas in the admin(fixed in the develop branch).:
```
# Remove trailing slashes
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} (.*)/$
RewriteCond %{REQUEST_URI} !fuel/.*$
RewriteRule ^(.*)/$ $1 [R=301,L]
```

Or the simplified version without ignoring the fuel folder
```
RewriteRule ^(.*)/$ /$1 [L,R=301]
```

**Comment by jpswade** [comment]
Did you commit this change?

I couldn't see the commit.

**Comment by daylightstudio** [comment]
No this was not committed but was just a suggestion. In my opinion this may not be desirable for every situation and seems outside of the realm of what FUEL should control by default.

**Comment by jpswade** [comment]
In what given situation would you deliberately want to serve both?

**Comment by daylightstudio** [comment]
Not necessarily both but the decision as to whether to include the slash or not is an individual preference. Setting up this redirect can have consequences on custom coding as well (e.g. ajax requests that end in a slash and are redirected which was the problem we were seeing in FUEL).

**Comment by jpswade** [comment]
Though you could tackle this situation by adding conditions:

```
RewriteCond %{HTTP:X-Requested-With} !=XMLHttpRequest
RewriteCond %{HTTP:X-REQUESTED-WITH} !^(XMLHttpRequest)$
```

However, having checked some of the most popular websites, I've found that it's about a 50/50 chance  that the trailing slash will display duplicate content or handled (different content, error or redirect).

Feel free to close this, at least until something more decisive is established.
