### ISSUE TITLE
Blog output page issue

### ISSUE THREAD

**Issue by grafxflow** [daylightstudio/FUEL-CMS#324]
I had an error appearing when listing blog posts.

```
Severity: Notice

Message: Undefined index: blog_links

Filename: libraries/Fuel_blog.php

Line Number: 983
```

I managed to sort it by changing the line 983 in the blog/libraries/Fuel_blog.php

```
$where[$tables['blog_links'].'.published'] = 'yes';
```

to

```
$where['published'] = 'yes';
```

**Comment by daylightstudio** [comment]
This issue should be fixed in the develop branch along with issue #326 that you reported.
