### ISSUE TITLE
Display Name not appearing Full Name appearing

### ISSUE THREAD

**Issue by grafxflow** [daylightstudio/FUEL-CMS#325]
If I create an author. Currently their display name does not appear in the published by. Is this normal?

```
Published June 07, 2015 by First Name - Last Name
```

instead of

```
Published June 07, 2015 by Display Name
```

This can be changed in modules/blog/views/themes/default/posts.php line 14 plus other...

```
by <strong><span class="post_author_name"><?=$post->author_name?></span></strong>
```

to

```
by <strong><span class="post_author_name"><?=$post->display_name?></span></strong>
```

**Comment by daylightstudio** [comment]
It's a preference that can be changed in the template like you just displayed.
