### ISSUE TITLE
Missing timestamp from ?c= query string appended to assets PHP 5.3

### ISSUE THREAD

**Issue by jpswade** [daylightstudio/FUEL-CMS#330]
The ?c= query string that is appended to assets is missing the timestamp.

The requirements say PHP version 5.2 or greater.
- http://docs.getfuelcms.com/installation/requirements

The server is running PHP version 5.3.25.

My local version is PHP version 5.6.8, which works fine.

I also found this problem in the wild on memoniac.com which is running Fuel CMS and PHP 5.4.16.

I'm looking at this file:
- https://github.com/daylightstudio/FUEL-CMS/blob/develop/fuel/modules/fuel/libraries/Asset.php#L478

**Comment by daylightstudio** [comment]
Is there a valid date specified for the "assets_last_updated" config value in fuel/application/config/asset.php?

**Comment by jpswade** [comment]
```
$config['assets_last_updated'] = '00/00/0000 00:00:00';
```

**Comment by daylightstudio** [comment]
If you change it to today's date, does it work?

**Comment by wilsonglasser** [comment]
Why not use the  last modified date from each file?

Em quinta-feira, 25 de junho de 2015, David McReynolds <
notifications@github.com> escreveu:

> If you change it to today's date, does it work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daylightstudio/FUEL-CMS/issues/330#issuecomment-115293809>
> .
>


-- 

Atenciosamente,
Wilson Glasser

**Comment by daylightstudio** [comment]
The main reason why we haven't made that change is because it requires a little extra overhead to get that information from the file system on each request.

**Comment by jpswade** [comment]
I'm sure changing that value might work, but I don't think it will solve the problem.

Nobody is going to know to update that file each time assets are updated.

Having a look at view-source:http://www.getfuelcms.com/ I can see the cache query is the same on each asset, for example:

```
	<link href="/assets/css/main.css?c=-62169955200" media="all" rel="stylesheet"/>
		<link href="/assets/css/home.css?c=-62169955200" media="all" rel="stylesheet"/>
```

The issues are:

* Both files are sharing the same cache timestamp even though it's unlikely that these files were updated at the same time.
* Both files have "-62169955200" appended, which doesn't appear to be a valid time.

I can understand your point about overheads in doing a filemtime query on the file system, but I don't see any other reliable way of generating a cache hash.

**Comment by jpswade** [comment]
Using zero values in the date string such as 00/00/0000 00:00:00 in strtotime() is a terrible idea.

* ["00-00-00 means 2000-00-00, which is 1999-12-00, which is 1999-11-30."](https://bugs.php.net/bug.php?id=45647)

```
echo strtotime('00/00/0000 00:00:00'); // -62169985172
```

```
echo date('Y-m-d H:i:s', strtotime('00/00/0000 00:00:00')); // -0001-11-30 00:00:00
```

```
echo date('Y-m-d H:i:s', -62169955200); // -0001-11-30 08:19:32
```

This doesn't seem like expected behaviour...

**Comment by daylightstudio** [comment]
The "00/00/0000 00:00:00" is a placeholder until the developer changes the timestamp to break the cache. You are right in that it will change the cache across all file types specified in the "asset_append_cache_timestamp" asset config value. (default are CSS and JS files). It's possible to setup perhaps a separate grunt or gulp task to update that value in the config upon file change.

**Comment by jpswade** [comment]
My point is that "00/00/0000 00:00:00" is a terrible placeholder to use as it is leading to unexpected behaviour.

If you're going to use a date format, you may want to stick to the MySQL format "Y-m-d H:i:s" as this will avoid some common problems and works well with the strtotime() function.

You might want to consider using UNIX EPOCH as the placeholder instead to avoid unexpected behaviour.

However, I do think caching this way is a terrible idea.

It would probably be better to handle it at [.htaccess level](http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/) anyway.

**Comment by daylightstudio** [comment]
What's the unexpected behavior?

**Comment by jpswade** [comment]
I'm sure nobody expects "00/00/0000 00:00:00" to be a valid date. It should be a deliberate value such as a valid date or FALSE, then the placeholder or input mask can be put in the comments.

Additionally, [query strings can break proxying](http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/). The web has much better cache controls (eg: Last-Modified or ETag) these days and query strings aren't necessary these days. Let the web server do it's job.

Going back to the original issue, which is that the cache query string is missing, which remains unexplained.

Having tested [echo strtotime('00/00/0000 00:00:00');](https://3v4l.org/Z5IGD) across all systems, which returns the integer -62169985172, while on [32-bit systems](http://codepad.org/HvyOoQ1a) you get a [value](http://codepad.org/hXVuAtbr) of 943920000.

"[The valid range of a timestamp is typically from Fri, 13 Dec 1901 20:45:54 UTC to Tue, 19 Jan 2038 03:14:07 UTC. (These are the dates that correspond to the minimum and maximum values for a 32-bit signed integer.)](http://php.net/strtotime)"

I suspect that is part of the problem.

Also "[To avoid potential ambiguity, it's best to use ISO 8601 (YYYY-MM-DD) dates](http://php.net/strtotime)".

**Comment by daylightstudio** [comment]
Remember, using this is optional and can be turned off in cases where it may be an issue with proxying. What is there now is simply a placeholder and can actually be changed to the YYYY-MM-DD format if the user decides to do so. I see this as a very minor issue. Changing this default may actually do more harm then good because it will create merge conflicts for folks that pull in the change.

**Comment by jpswade** [comment]
OK.

I can't seem to replicate the original issue in v1.3, so I assume that it's being fixed.

However, I would advise that if assets_last_updated is "00/00/0000 00:00:00", then it is turned off.

```
$check =  (int) filter_var("00/00/0000 00:00:00", FILTER_SANITIZE_NUMBER_INT); // returns 0
```

This solves your merge conflicts issue.

My view is that changing the date format might seem like a minor issue now, but it will save you headaches in future if you stick to the standards.
