### ISSUE TITLE
Is it possible to add some filter to simple model module

### ISSUE THREAD

**Issue by SunYunSoft** [daylightstudio/FUEL-CMS#331]
Hi

This CMS really benefit our project. But we met one issue for filtering the data, there is the search window for the module. But sometimes, we may need to define some filter to filter data, is it possible.

For example, there are thousands of user in one table, and belongs to different group, we want filter people based on the group.

**Comment by daylightstudio** [comment]
Try this section in the documentation:
http://docs.getfuelcms.com/modules/simple#filtering

**Comment by SunYunSoft** [comment]
Sorry for late reply.

It is really a great feature and help us a lot.
