### ISSUE TITLE
Can i make ecommerce website with FUEL CMS??

### ISSUE THREAD

**Issue by Kanasagra-Jaydip** [daylightstudio/FUEL-CMS#336]
I want to create e-Commerce site with FUEL CMS is this possible??

if yes so how this possible. can you give me any reference URL??

**Comment by daylightstudio** [comment]
It is possible but requires a bit of work. You would need to create your own modules (e.g. product, categories, transactions, etc). I'd recommend reading the documentation on modules for more information:
http://docs.getfuelcms.com/modules

In the forum, there are a few threads that have a small amount of additional information:
http://forum.getfuelcms.com/discussion/comment/5994#Comment_5994
http://forum.getfuelcms.com/discussion/comment/2952#Comment_2952
