### ISSUE TITLE
Form_builder - Create a read_only field

### ISSUE THREAD

**Issue by pixelice** [daylightstudio/FUEL-CMS#337]
<div id="error_php" style="width: 500px; margin: auto; border: 1px solid #ddd; padding: 20px;">

	<h1 style="margin: 0; padding:0; font-family: Arial,Helvetica,sans-serif; font-size: 22px; color: #999; font-weight: normal; padding: 10px 4px 5px 0;">A PHP Error was encountered</h1>
	<p>Severity: Notice</p>
	<p>Message:  Undefined variable: val</p>
	<p>Filename: libraries/Form_builder.php</p>
	<p>Line Number: 2759</p>

</div>

I suppose that in Form_builder, instead of method:

public function create_readonly($params)
	{
		$params = $this->normalize_params($params);
		$str = $params['value']."\n".$this->create_hidden($val);
		return $str;
	}

should be:

public function create_readonly($params)
	{
		$params = $this->normalize_params($params);
		$str = $params['value']."\n".$this->create_hidden($params);
		return $str;
	}

**Comment by daylightstudio** [comment]
Thanks for the report. A fix has been posted in the develop branch (and 1.4_dev branch which includes CI 3.0) and will be in the next release.
