### ISSUE TITLE
Pagination query string issue

### ISSUE THREAD

**Issue by jpswade** [daylightstudio/FUEL-CMS#338]
Pagination should look like this:

* http://www.example.com/path?page=1
* http://www.example.com/path?page=2
etc

Instead it looks like this:

* http://www.example.com/path&page=1
* http://www.example.com/path&page=2

The problem was outlined in [CodeIgniter issue #1817](https://github.com/bcit-ci/CodeIgniter/issues/1817) and [fixed](https://github.com/bcit-ci/CodeIgniter/commit/6b4e3624b9a33c144b3ab4aea7904d5919fcc306#diff-8e44b771abcb1284fb55e6e805f4ef06), however [Fuel CMS](https://github.com/daylightstudio/FUEL-CMS/blob/develop/fuel/codeigniter/libraries/Pagination.php#L218) remains unfixed.

**Comment by daylightstudio** [comment]
The Pagination library that's being used is the CI 2.2.1 which is the current version FUEL is on for the Master branch. That fix looks to be tagged for the 3.0 release.  FUEL CMS on CI 3.0 is currently in a dev feature branch here:
https://github.com/daylightstudio/FUEL-CMS/tree/feature/1.4_dev

**Comment by jpswade** [comment]
The fix mentioned works in Fuel CMS.
