### ISSUE TITLE
Fuel_navigation upload Fatal error [PHP 5.3]

### ISSUE THREAD

**Issue by jpswade** [daylightstudio/FUEL-CMS#340]
Steps to reproduce on PHP 5.3:

1. Go to /fuel/navigation/upload
2. Upload your nav.php

You'll get the following errors:

```
A PHP Error was encountered
Severity: Warning

Message: Attempt to assign property of non-object

Filename: libraries/Fuel_navigation.php

Line Number: 469

Fatal error: Call to a member function save() on a non-object in /var/www/xxx/fuel/modules/fuel/libraries/Fuel_navigation.php on line 470
```

**Comment by daylightstudio** [comment]
Was this with a fresh install? Does your fuel_navigation_groups table have any records in it? By default it should have one for a main navigation group.

**Comment by jpswade** [comment]
That table was empty.
```
INSERT INTO `fuel_navigation_groups` (`id`, `name`, `published`) VALUES ('1', 'main', 'yes');
```

That fixed it.

Perhaps it should create the main group if it doesn't exist and it's selected from the dropdown?

**Comment by daylightstudio** [comment]
Yeah. I've already posted a fix for that in the dev branch to create it if it doesn't exist. We mysteriously ran into the same issue a couple weeks ago.

**Comment by jpswade** [comment]
I see it here:

https://github.com/daylightstudio/FUEL-CMS/commit/bf22a673eee032515370a82d4ada46209fd608e7
