### ISSUE TITLE
Value needs to be a number for 'group id'.

### ISSUE THREAD

**Issue by jpswade** [daylightstudio/FUEL-CMS#341]
When working with `$this->fuel->navigation->upload();` you may come across this validation error from the save:

`Array ( [group_id] => Value needs to be a number for 'group id'. )`

To fix this, you need to add the following line `$group_id = $group->id;` after [fuel/modules/fuel/libraries/Fuel_navigation.php#L473](https://github.com/daylightstudio/FUEL-CMS/blob/develop/fuel/modules/fuel/libraries/Fuel_navigation.php#L473).

This will ensure that the group_id is always the id from the $group object, rather than string version.

**Comment by daylightstudio** [comment]
This issue may already have been addressed in the develop branch:
https://github.com/daylightstudio/FUEL-CMS/commit/bf22a673eee032515370a82d4ada46209fd608e7

**Comment by jpswade** [comment]
Not quite.

The issue is at [L498](https://github.com/daylightstudio/FUEL-CMS/blob/bf22a673eee032515370a82d4ada46209fd608e7/fuel/modules/fuel/libraries/Fuel_navigation.php#L498), where $group_id is used.

If you look at L411, group_id is a string of 'main', which is then extracted at line L433.

As we're doing a $group object lookup, we might as well set `$group_id = $group->id;` to ensure it's an real int.

**Comment by daylightstudio** [comment]
I see what you are saying. Take it to below the conditional `if (!isset($group->id))` statement correct?

**Comment by jpswade** [comment]
Yes, that's right.

Take `$group_id = $group->id` out of the `if (!isset($group->id))` and place below fixes it for me.

I should have done a push ;)

**Comment by daylightstudio** [comment]
A fix has been pushed to the develop branch and the 1.4_dev branch (CI 3.0)

**Comment by jpswade** [comment]
Has development for "develop" stopped?

If so, when are you hoping to merge 1.4 to master?

**Comment by daylightstudio** [comment]
develop is essentially a 1.3.1 update that contains a number of bug fixes and will be released here probably within the month. 1.4_dev needs some further testing because of the large amount of changes to make it compatible with CI 3.0  (so please feel free to test out if you can). All 1.3.1 changes are being synced with 1.4_dev

**Comment by jpswade** [comment]
We've tested 1.4_dev and it fell over, even after a bit of coercion to get it setup - but that's a separate matter.

That's why I'm keen to stick with the develop branch for now until 1.4_dev has had a little more testing.

**Comment by daylightstudio** [comment]
Is this recently (like within the last few weeks)?

**Comment by jpswade** [comment]
Yes. I'll spin up a test copy later this week and report back.

Cheers.
