### ISSUE TITLE
exceedes

### ISSUE THREAD

**Issue by jpswade** [daylightstudio/FUEL-CMS#347]
> The image you are attempting to upload exceedes the maximum height or width.

Should be:

> The image you are attempting to upload exceeds the maximum height or width.

https://github.com/daylightstudio/FUEL-CMS/blob/master/fuel/codeigniter/language/english/upload_lang.php#L13

**Comment by daylightstudio** [comment]
Thanks for the report. This fix has been pushed to the develop branch and will be in the next release.
