### ISSUE TITLE
required file not found

### ISSUE THREAD

**Issue by bigredradish** [daylightstudio/FUEL-CMS#348]
I've just done a fresh install of version 1.3.1 and get the following error on the index page (and admin page - but can log in):

Fatal error: require_once(): Failed opening required '.../fuel/application/../modules/fuel/helpers/MY_directory_helper.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in .../fuel/application/helpers/MY_directory_helper.php on line 3

is this a known bug?

**Comment by daylightstudio** [comment]
Does the file fuel/modules/fuel/helpers/MY_directory_helper.php exist in your install?

**Comment by bigredradish** [comment]
interestingly - it exists in the local extracted archive but will not upload to server (have just tried multiple times with different permission on the helpers folder)

**Comment by bigredradish** [comment]
think it must be something to do with the file itself even if I rename it and try to upload it the upload fails (can however rename other files e.g. google_helper.php and they upload fine...)

**Comment by daylightstudio** [comment]
If you remove the contents of the file, does it upload?

**Comment by bigredradish** [comment]
yes - if I upload an empty file it stays in the directory on the server - if I then edit the file on the server and add the contents of the original file it disappears from the server again

**Comment by bigredradish** [comment]
Have narrowed it down to the 'copyr' and 'chmodr' functions - think my server must scan the files and not like those functions and automatically delete it...

**Comment by daylightstudio** [comment]
Interesting... never heard of that before.
