### ISSUE TITLE
Cookies are too big

### ISSUE THREAD

**Issue by earlymarket** [daylightstudio/FUEL-CMS#349]
Fuel breaks Cloudflare because (according to Cloudflare) it produces cookies that are too big and hence an ERR_CONNECTION_RESET

From Cloudflare: 
Jeremy Meeks (CloudFlare)
Oct 29, 12:24 AM

An Error 520 happens when your origin returns a response that is unexpected, generally when your web server returned an invalid response that exceeded our limits. This can happen if your web server is returning too many/too large headers, often caused by runaway scripts that return too many cookies, for example. The Code Igniter PHP framework has some known bugs around this, unfortunately.

**Comment by daylightstudio** [comment]
There are a couple things you can try to reduce the cookie size:
1. Change the fuel/application/config/config.php database information to store the sessions in the database:
https://ellislab.com/codeigniter/user-guide/libraries/sessions.html
2. Add the following to your MY_fuel.php
```
// Max number of recent pages to display
$config['max_recent_pages'] = 0;

// The maximum number of pages that page state will be saved before dumping the last one saved.
// This is used on the list pages in the admin to save sorting and filtering. Used to save on space needed for session.
$config['saved_page_state_max'] = 0;
```
