### ISSUE TITLE
Upgrade FUEL-CMS to CodeIgniter v3?

### ISSUE THREAD

**Issue by salmanaligeek** [daylightstudio/FUEL-CMS#351]
Hi,

I am planning to develop an e-commerce module using flexi cart in FUEL-CMS. But FUEL-CMS is built on CodeIgniter version 2.2.1 and it is not even the latest version of 2.x branch and CI v2 has reached end-of-life. So how I can upgrade FUEL-CMS to CI v3?
Has any user of FUEL-CMS tried to upgrade yet? I want to know what kind of problems FUEL-CMS users faced while upgrading?

**Comment by daylightstudio** [comment]
Use the 1.4_dev branch.
https://github.com/daylightstudio/FUEL-CMS/tree/feature/1.4_dev

**Comment by salmanaligeek** [comment]
When 1.4_dev branch become stable?

**Comment by daylightstudio** [comment]
Tough to say but hopefully soon. Needs some more vetting by the community. At this point there are no known errors and changes to develop branch are being merged into that 1.4_dev branch.

**Comment by SystemDisc** [comment]
Does the latest stable version use CodeIgnter 3.x?

**Comment by daylightstudio** [comment]
Yes
