### ISSUE TITLE
It does not work request block from the module

### ISSUE THREAD

**Issue by jeka5555** [daylightstudio/FUEL-CMS#352]
I want to display on the home page of the block "arhives" from the module blogs.

The layout main.php I do so:
fuel_block(array('view' => 'archives', 'module' => 'blog'));

but returns an empty string.

I checked the library Fuel Blocks, and found that the variable $view_path It has the wrong path. The path does not include the theme folder: "/themes/default"

**Comment by jeka5555** [comment]
It works like this:

$this->load->module_view('blog', 'themes/default/_blocks/archives');

**Comment by daylightstudio** [comment]
There is a blog_block function you can use for blog blocks since they use a different folder structure and it needs to take into account the selected theme.
