### ISSUE TITLE
automatic installation!

### ISSUE THREAD

**Issue by ZeoNish** [daylightstudio/FUEL-CMS#353]
Make the automatic installation of a CMS... It will be very useful!

**Comment by ZeoNish** [comment]
All CMS's have an auto setting.

**Comment by daylightstudio** [comment]
FUEL does have a CLI installer for mac/unix environments at:
`>php index.php fuel/installer/install`

**Comment by ZeoNish** [comment]
I meant for the average user.

**Comment by ZeoNish** [comment]
for example I never got to install your cms...

**Comment by daylightstudio** [comment]
FUEL is geared a little more towards developers who are familiar with working in a CodeIgniter environment so it may not be the right fit for you.

**Comment by ZeoNish** [comment]
ok....
