### ISSUE TITLE
Get rid of fuel url suffix

### ISSUE THREAD

**Issue by ronlinet** [daylightstudio/FUEL-CMS#354]
How can we get rid of the default “fuel” suffix which is being appended at the end of the url after a new installation => http://new-fuel-install.com/fuel? I have tried to walk around with redirecting apache to “fuel” folder instead of web-root but I end up with a redirecting loop error. What is the approach to get a normal clean installation without the “fuel” suffix?

**Comment by michelMuv** [comment]
Ok so I answer my question. 
To change override the default /fuel suffix you have to modify the $config['fuel_path'] variable of in My_fuel.php file.  
To change the landing page you simply modify the fuel/application/views/_layouts/main.php to what ever you want.

**Comment by ronlinet** [comment]
Ok so I answer my question.

To change the default /fuel suffix you have to modify the $config['fuel_path'] variable of in My_fuel.php file.

To change the landing page you simply modify the fuel/application/views/_layouts/main.php to what ever you want.

**Comment by andylow** [comment]
These stated in Fuel CMS documentation, you should check it out : 
http://docs.getfuelcms.com/general/constants
http://docs.getfuelcms.com/installation/configuration

So I think this issue can be closed.
