### ISSUE TITLE
Enabling "assets_output" produces wrong path.

### ISSUE THREAD

**Issue by jsieler** [daylightstudio/FUEL-CMS#355]
Hello!
I've enabled in "asset.php" config following line "assets_output = TRUE". The result is, path to cache file include no "cache/" folder.
Result is
```<link href="/assets/58dcc8d5087d113300770b1999c9547c_-62169955200.php" media="all" rel="stylesheet"/>```
instead of
```<link href="/assets/cache/58dcc8d5087d113300770b1999c9547c_-62169955200.php" media="all" rel="stylesheet"/>```
Any fix?

**Comment by daylightstudio** [comment]
Is the cache folder writable?

**Comment by jsieler** [comment]
Yes, it is definitely writeable, and files are created. The only problem is
returned path doesn't contain cache directory.

Simple check, put fresh CMS, visit installer (no install needed) see it
working. Go to assets config and turn output to true. Refresh page and you
will see no styling at all. Check source and see the cached files path.
20 янв. 2016 г. 19:48 пользователь "David McReynolds" <
notifications@github.com> написал:

**Comment by daylightstudio** [comment]
I've pushed a fix for this here:
https://github.com/daylightstudio/FUEL-CMS/commit/e67837584e2b2f1fce68d754e8b01cf38f852554

Basically, add a cache folder to fuel/application/config/assets.php file `$config['assets_folders']` and change the `$config['assets_cache_folder'] = 'cache/';` to `$config['assets_cache_folder'] = 'cache';`
