### ISSUE TITLE
wysiwyg field 'preview' view file doesn't work on ckeditor first load.

### ISSUE THREAD

**Issue by andylow** [daylightstudio/FUEL-CMS#358]
I found that 'preview' view file is working fine in ckeditor if switch to 'source' view click on preview, after that switch back 'editor' view click on preview is ok.
However if I click on preview on 1st load (without switch to 'source' view), the specified preview file is not loaded.

**Comment by daylightstudio** [comment]
What version of FUEL are you using (you can check the fuel/modules/fuel/config/fuel_constants.php file)?

**Comment by andylow** [comment]
version 1.3.1
