### ISSUE TITLE
Assets loaded using absolute path don't respect page protocol (http/https)

### ISSUE THREAD

**Issue by dgohlke** [daylightstudio/FUEL-CMS#363]
I discovered a problem when trying to call an assets with an absolute path. If the page is loaded over HTTPS, the asset is still loaded over HTTP, causing [mixed content](https://developer.mozilla.org/en-US/docs/Security/Mixed_content).

Example JS call: `<?=js($this->asset->js_path('main', NULL, TRUE)); ?>`

The below code change [here](https://github.com/daylightstudio/FUEL-CMS/blob/master/fuel/modules/fuel/libraries/Asset.php#L503)  in `fuel/modules/fuel/libraries/Asset.php` can remedy this:

```
-            $path = 'http://'.$_SERVER['HTTP_HOST'].$path;

+            $protocol = ($_SERVER["SERVER_PORT"] == 443) ? "https://" : "http://";
+            $path = $protocol.$_SERVER['HTTP_HOST'].$path;
```

I can submit this via a pull request if you prefer.

**Comment by daylightstudio** [comment]
Thanks for the report. I'll push a fix shortly.

**Comment by dgohlke** [comment]
It might be a better idea to use $_SERVER['HTTPS'] instead of $_SERVER["SERVER_PORT"]. But there are apparently some quirks with that.
