### ISSUE TITLE
Consider adding ci_sessions table to fuel_schema.sql

### ISSUE THREAD

**Issue by dgohlke** [daylightstudio/FUEL-CMS#365]
Please consider adding `ci_sessions` table schema to https://github.com/daylightstudio/FUEL-CMS/blob/master/fuel/install/fuel_schema.sql.

If someone changes https://github.com/daylightstudio/FUEL-CMS/blob/master/fuel/application/config/config.php#L251 to `TRUE`, they'll get a database error because the ci_sessions table isn't included in the schema.

Additionally, if someone searches Google for FuelCMS ci_sessions, [this discussion](http://forum.getfuelcms.com/discussion/comment/4990#Comment_4990) appears with an outdated ci_sessions schema. the CI schema changed at some point and the CI application code in Fuel  was updated ([here](https://github.com/daylightstudio/FUEL-CMS/commit/8c2d46499b859752a90e25bdd736a1bd74599984#diff-6b5ec915f4cda32330ae61331fcdbff7R192)) without a corresponding schema change.

I debugged a problem this morning where my ci_sessions table had a `user_agent` field defined as the old varchar(50) instead of the new varchar(120). The application was trying to match the first 120 characters but the database was only storing the first 50 characters. So sessions weren't being matched properly, and I couldn't log into Fuel.

I believe this is a current ci_session schema: 

```
DROP TABLE IF EXISTS `ci_sessions`;
CREATE TABLE `ci_sessions` (
  `session_id` varchar(40) NOT NULL DEFAULT '0',
  `ip_address` varchar(16) NOT NULL DEFAULT '0',
  `user_agent` varchar(120) NOT NULL,
  `last_activity` int(10) unsigned NOT NULL DEFAULT '0',
  `user_data` text,
  PRIMARY KEY (`session_id`)
)
```

**Comment by daylightstudio** [comment]
Only tricky thing with this is that the developer also needs to determine which type of key to used on the table:
```
# When sess_match_ip = TRUE
ALTER TABLE ci_sessions ADD PRIMARY KEY (id, ip_address);
# OR 
# When sess_match_ip = FALSE
ALTER TABLE ci_sessions ADD PRIMARY KEY (id); 
```

**Comment by dgohlke** [comment]
Well, I don't think you would want a primary key on session_id and ip_address because multiple people could access a site behind the same IP address, and the primary key would cause a constraint that doesn't allow it.

If the concern was speed of session matching, wouldn't adding an index on `session_id, ip_address` alleviate that? Or for that matter `session_id, ip_address, user_agent` if `$config['sess_match_useragent']` is also `true`?

**Comment by daylightstudio** [comment]
I was just referring to the CI documentation found here:
https://codeigniter.com/user_guide/libraries/sessions.html#database-driver

**Comment by dgohlke** [comment]
I have updated my previous comment. Having a primary key on id and ip_address won't cause any problems as the primary key also contains the id. Sorry. I forgot databases 101 for a minute there.

So maybe the solution is to include the ci_sessions table in the db schema and add the primary key appropriate for whatever `$config['sess_match_useragent']` is set to. Then add a comment indicating the primary key should be modified if `$config['sess_match_useragent']` is changed.
