### ISSUE TITLE
Error on installation page - using latest develop branch

### ISSUE THREAD

**Issue by unuigbee** [daylightstudio/FUEL-CMS#366]
The Installation page loads fine but this error seems to accompany the installation page.

```
Severity: Notice

Message: Array to string conversion

Filename: libraries/Fuel_navigation.php

Line Number: 250

Backtrace:

File: /home/unuigbee/public_html/edwardstreetparish/fuel/modules/fuel/libraries/Fuel_navigation.php
Line: 250
Function: _error_handler

File: /home/unuigbee/public_html/edwardstreetparish/fuel/modules/fuel/helpers/fuel_helper.php
Line: 158
Function: render

File: /home/unuigbee/public_html/edwardstreetparish/fuel/application/views/_variables/global.php
Line: 9
Function: fuel_nav

File: /home/unuigbee/public_html/edwardstreetparish/fuel/modules/fuel/libraries/Fuel_pagevars.php
Line: 160
Function: require

File: /home/unuigbee/public_html/edwardstreetparish/fuel/modules/fuel/libraries/Fuel_pagevars.php
Line: 85
Function: view

File: /home/unuigbee/public_html/edwardstreetparish/fuel/modules/fuel/libraries/Fuel_pages.php
Line: 728
Function: retrieve

File: /home/unuigbee/public_html/edwardstreetparish/fuel/modules/fuel/libraries/Fuel_pages.php
Line: 574
Function: assign_variables

File: /home/unuigbee/public_html/edwardstreetparish/fuel/modules/fuel/libraries/Fuel_pages.php
Line: 525
Function: initialize

File: /home/unuigbee/public_html/edwardstreetparish/fuel/modules/fuel/libraries/Fuel_pages.php
Line: 65
Function: __construct

File: /home/unuigbee/public_html/edwardstreetparish/fuel/modules/fuel/controllers/Page_router.php
Line: 43
Function: create

File: /home/unuigbee/public_html/edwardstreetparish/index.php
Line: 365
Function: require_once
```

**Comment by daylightstudio** [comment]
This is with a fresh copy of the develop branch? I'm not able to replicate this issue at the moment.

**Comment by unuigbee** [comment]
Yes this is a fresh copy for CI 3.0.6. Ah ok I'll see what might have caused the issue in the mean time.

**Comment by unuigbee** [comment]
Ah this error pertains to any non-admin view that's rendered and handled by fuel navigation.

**Comment by daylightstudio** [comment]
I meant, is this a fresh copy of the FUEL develop branch (not CI)

**Comment by daylightstudio** [comment]
What is the value being converted to a string (you can debug right before line 250 in that class)?

**Comment by unuigbee** [comment]
Yes I'm using a fresh copy of the Fuel develop branch. I think I've figured it out - on line 250 we have this: `$items = (!empty($$p['var'])) ? $$p['var'] : array();`

The issue is this particular expression here: `$$p['var'] ` it seems to be referencing an array and trying to convert it to a string/variable which causes an _Array to String conversion_ notice but it simple falls to a null value. 

On line 171 we have this expression: `$$p['var'] = array();` Hence it's trying make the value `array();` into a variable as specified by the $$.

Try this piece of code out on [phpfiddle](http://phpfiddle.org/ ) and you'll get the same error notice:
```
$p = array(array());
var_dump($$p[0]); 
``` 
I guess it's just my error reporting that's making noise about this. Maybe due to my PHP version which is PHP v7.05

**Comment by daylightstudio** [comment]
That does look to be a PHP v7 issue. I've pushed a fix found here (under variable variables):
http://php.net/manual/en/migration70.incompatible.php

**Comment by unuigbee** [comment]
Thanks works like a charm
