### ISSUE TITLE
Assets section on Admin Dashboard rendering issues

### ISSUE THREAD

**Issue by unuigbee** [daylightstudio/FUEL-CMS#368]
I also checked the console and it says there are two reference errors to jQuery. Not sure if that is partly causing the render issues. 

<img width="960" alt="screenshot 2016-04-23 17 43 20" src="https://cloud.githubusercontent.com/assets/6902308/14762762/fa2fca22-097a-11e6-8b54-3b8fbf331a69.png">

**Comment by hemingweb** [comment]
In my experience the best way rot start debuting this is to view the source around the top right of the screen. I suspect there is an issue with one of your modules. As a quick you could comment out your modules in the config/MY_fuel_modules

**Comment by unuigbee** [comment]
Thanks for the tip. However I have no modules because i'm using a fresh installation from the dev branch but ill have a look anyway.

**Comment by hemingweb** [comment]
What is the start page saying? Have you been through the setup steps?

**Comment by unuigbee** [comment]
Yh I've been through the setup steps and it went ok. However there are error messages posted on various pages like the start up/instruction page.

Edit: It seems there are new commits addressing the error messages i've been having. I'll try it out and see if it fixes anything.

**Comment by unuigbee** [comment]
Ah it seems to have been fixed with the latest dev branch commits.
