### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by arkilis** [daylightstudio/FUEL-CMS#370]
I follow up the introduction on the webpage as following, where http://server/FUEL-CMS/fuel/start does not work

=============

Change the Apache .htaccess file

Change the Apache .htaccess found at the root of FUEL CMS's installation folder to the proper RewriteBase directory. The default is your web server's root directory (e.g "/"), but if you have FUEL CMS installed in a sub folder, you will need to add the path to line 5. If you are using the folder it was zipped up in from GitHub, it would be RewriteBase /FUEL-CMS-master/.

In some server environments, you may need to add a "?" after index.php in the .htaccess like so: RewriteRule .* index.php?/$0 [L]

NOTE: This is the only step needed if you want to use FUEL without the CMS.

2
Install the database

Install the FUEL CMS database by first creating the database in MySQL and then importing the fuel/install/fuel_schema.sql file. After creating the database, change the database configuration found in fuel/application/config/database.php to include your hostname (e.g. localhost), username, password and the database to match the new database you created.

3
Make folders writable

Make the following folders writable (666 = rw-rw-rw, 777 = rwxrwxrwx, etc.):

/var/www/html/FUEL-CMS/fuel/application/cache/
(folder for holding cache files)
/var/www/html/FUEL-CMS/fuel/application/cache/dwoo/
(folder for holding template cache files)
/var/www/html/FUEL-CMS/fuel/application/cache/dwoo/compiled
(for writing compiled template files)
/var/www/html/FUEL-CMS/assets/images
(for managing image assets in the CMS)
4
Make configuration changes

In the fuel/application/config/MY_fuel.php file, change the $config['admin_enabled'] configuration property to TRUE. If you do not want the CMS accessible, leave it as FALSE.
In the fuel/application/config/MY_fuel.php file, change the $config['fuel_mode'] configuration property to AUTO. This must be done only if you want to view pages created in the CMS.

**Comment by daylightstudio** [comment]
Please provide errors or specifics to what is happening instead.

**Comment by arkilis** [comment]
The error is: in the instruction, set $config['fuel_mode'] = 'AUTO'; there will be blank page output. 

when change it back to $config['fuel_mode'] = 'views'; it will show some pages, but pages such as 

http://192.168.2.227/FUEL-CMS/index.php/fuel/login/5a6e566c62413d3d

is always blank.

**Comment by arkilis** [comment]
Alright, don't bother with this. I finally found out myself. For people who might meet this in future. This is due to some missing libs, so trying to install:

sudo apt-get install php5-mysql
