### ISSUE TITLE
www.example.com/fuel shows a could not open input file: fuel/installer/update

### ISSUE THREAD

**Issue by unuigbee** [daylightstudio/FUEL-CMS#371]
When I request this url **www.example.com/fuel** in a browser it shows a page with this error: `could not open input file: fuel/installer/update`. It's strange because I thought it would automatically route to the login page for the dashboard. I'm wondering why its showing this error as I have already installed the CMS. 

I guess I can get around this by making a custom route that routes this request to the login page or home page.

**Comment by daylightstudio** [comment]
Is this with the develop branch or the master branch? Also, does this happen with fresh copies?

**Comment by unuigbee** [comment]
It's with the develop branch? No it doesn't happen with fresh copies.

**Comment by daylightstudio** [comment]
Are there any changes you may have made to your version that you think may have caused the issue?

**Comment by unuigbee** [comment]
Ah that's strange. Within the fuel/index.php file it says **Could not open input file: fuel/installer/update**. However with a fresh installation fuel/index.php says: 
```
<?php
header('Location: start');
exit();
```
Not sure how it turned out like that but I've replaced the contents of the file with that piece of code and it seems to be working again.
