### ISSUE TITLE
Array to String Conversion error when creating new tags

### ISSUE THREAD

**Issue by unuigbee** [daylightstudio/FUEL-CMS#372]
Filename: core/MY_Model.php
Message:  Array to string conversion
Line Number: 3355

This error is due to PHP 7 error reporting based on [variable handling](http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling) 

`
$clear_on_save = ((strtoupper($this->clear_related_on_save) == 'AUTO' AND isset($this->normalized_save_data['exists_'.$related_field])) OR $this->clear_related_on_save === TRUE);`

Not really sure how you would provide backward compatibility for  `normalized_save_data['exists_'.$related_field])) ` where $related field is the array converted to a string.

**Comment by daylightstudio** [comment]
Could you provide steps on how to recreate the issue please.

**Comment by unuigbee** [comment]
The error occurs when creating new tags for blog posts via the Blog Module. The tag still gets created but that error shows during the process. I've tried this with both php 5 and 7 and the error only shows for version 7.

1. While creating a blog post click the associations tab
2. Click add for the tags section to create a new tag
3. Fill in the required tag fields 
4. Click save

**Comment by daylightstudio** [comment]
Thanks for the steps to reproduce the issue. A fix has been posted.
