### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by blupalmail** [daylightstudio/FUEL-CMS#374]
need help how to fix i am new to coding 
iam getting this error
## http://www.buymineralwater.in/mineralwaterbrands

A PHP Error was encountered

Severity: Notice

Message: Undefined variable: metakeywords

Filename: includes/header_v.php

Line Number: 11

Backtrace:

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/views/includes/header_v.php
Line: 11
Function: _error_handler

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/controllers/Blupal.php
Line: 884
Function: view

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/index.php
Line: 292
Function: require_once

" />
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: metadescription

Filename: includes/header_v.php

Line Number: 12

Backtrace:

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/views/includes/header_v.php
Line: 12
Function: _error_handler

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/controllers/Blupal.php
Line: 884
Function: view

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/index.php
Line: 292
Function: require_once

" />
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: ogdescription

Filename: includes/header_v.php

Line Number: 46

Backtrace:

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/views/includes/header_v.php
Line: 46
Function: _error_handler

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/controllers/Blupal.php
Line: 884
Function: view

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/index.php
Line: 292
Function: require_once

">
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: ogtitle

Filename: includes/header_v.php

Line Number: 48

Backtrace:

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/views/includes/header_v.php
Line: 48
Function: _error_handler

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/controllers/Blupal.php
Line: 884
Function: view

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/index.php
Line: 292
Function: require_once

">
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: ogurl

Filename: includes/header_v.php

Line Number: 51

Backtrace:

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/views/includes/header_v.php
Line: 51
Function: _error_handler

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/controllers/Blupal.php
Line: 884
Function: view

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/index.php
Line: 292
Function: require_once

">
Go Home
Track Your Complaint  
Enter Complaint Number

Book mineral water online
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: H1

Filename: views/brandlists.php

Line Number: 19

Backtrace:

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/views/brandlists.php
Line: 19
Function: _error_handler

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/application/controllers/Blupal.php
Line: 885
Function: view

File: /hermes/bosnaweb15a/b2485/ipg.navcosys/buymineralwater/index.php
Line: 292
Function: require_once

A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
Click for Pricing & Details 
Aqua Fresh
Click for Pricing & Details 
TAJA
Click for Pricing & Details 
SURYA

LOGIN | HOME | JOIN US | CONTACT US | FAQ | TERMS OF USER | PRIVACY & LEGAL POLICY | BOTTLED WATER COMPLAINT | SITEMAP | BRANDS
COPYRIGHT © BLUPAL. ALL RIGHTS RESERVED. BACK TO TOP

**Comment by daylightstudio** [comment]
The variable "metakeywords" needs to be defined in either the fuel/application/views/_variables/global.php file or as a field in the pages layout... actually there are a number of ways to do this.
