### ISSUE TITLE
Admin dashboard didn't load

### ISSUE THREAD

**Issue by tintutech** [daylightstudio/FUEL-CMS#380]
Hi Team,

I have installed fuel cms on my local system.
I followed the instruction for installation and click on the link for admin panel. But it gives me 404 error.

Appreciate your support to resolve this issue

**Comment by daylightstudio** [comment]
Did you set the admin to be enabled in fuel/application/config/MY_fuel.php?
```
// whether the admin backend is enabled or not
$config['admin_enabled'] = TRUE;
```

**Comment by tintutech** [comment]
Thanks.
It's working now.

**Comment by mudasserzahid** [comment]
I have completed the installation procedure, but admin penal is not loading
I am using xampp
