### ISSUE TITLE
404 error found on index.php

### ISSUE THREAD

**Issue by ranjeetranjan** [daylightstudio/FUEL-CMS#382]
Hi Team,

I have configured as per your guide but getting error 404.
404 Page Not Found
The page you requested was not found.
http://fuel.mysite.com/fuel/index.php/fuel

Please help on it.

**Comment by daylightstudio** [comment]
Did you turn on the admin in the fuel/application/config/MY_fuel.php?
```
$config['admin_enabled'] = TRUE;
```

**Comment by adsizzler** [comment]
Thanks for your prompt response.
It worked.

Thanks lot.
