### ISSUE TITLE
Error: You must make the /cache/dwoo/compiled/ folder writable. 

### ISSUE THREAD

**Issue by webdevnerdstuff** [daylightstudio/FUEL-CMS#383]
Error:
> You must make the /vagrant/public_html/fuel/application/cache/dwoo/compiled/ folder writable.

I have tried to change the permissions to _cache_, _dwoo_, and _compiled_ with the following commands, regular and recursive. All output the same error. Replacing ### with 766, 775, 776, and 777. None have worked. 

sudo chmod ### cache
sudo chmod ### cache/dwoo
sudo chmod ### cache/dwoo/compiled

sudo chmod -R ### cache
sudo chmod -R ### cache/dwoo
sudo chmod -R ### cache/dwoo/compiled

I have also changed permissions via SSH into the Vagrant box, as well as from outside the box on my Mac. I have also tried by deleting the cache directory and creating them fresh. 

I have looked at these two pages and tried everything suggested all with the same results.
http://forum.getfuelcms.com/discussion/11/making-folders-writable/p1
http://forum.getfuelcms.com/discussion/966/errors/p1

I'm somewhat out of ideas at this point. Any help would be appreciated. Thank you.

**Comment by daylightstudio** [comment]
What are the permissions for the following directories now?
fuel/application/cache/
fuel/application/cache/dwoo/
fuel/application/cache/dwoo/compiled/

It looks like it may be getting caught up on the line 43 of fuel/modules/fuel/libraries/parser/Fuel_dwoo_parser.php where it is checking if the folder is writable:
```
if (is_writable($this->compile_dir))
```

**Comment by webdevnerdstuff** [comment]
Currently they are

Inside Vagrant:
`drwxrwxr-x 1 vagrant  204 Nov 27 21:13 cache`

Mac:
`drwxrwxrwx@  6 username  204 Nov 27 13:13 cache`

**Comment by daylightstudio** [comment]
So can you verify in the code that `is_writable` is returning false (http://php.net/is_writable)  in fuel/modules/fuel/libraries/parser/Fuel_dwoo_parser.php on line 43? If so, do you have any sort of safe_mode set?

**Comment by webdevnerdstuff** [comment]
`is_writable($this->compile_dir)` Is returning FALSE.

I have looked all over and I don't see safe_mode set anywhere, and none set in any php.ini files inside or outside the VB.

**Comment by daylightstudio** [comment]
If you change out is_writable with the CI function `is_really_writable`, does it help?

**Comment by webdevnerdstuff** [comment]
Ok I finally got it figured out. So stupid on my part. In my Vagrant file I had:

`  config.vm.synced_folder "public_html", "/vagrant/public_html", :mount_options => ["dmode=775", "fmode=777"], :create => true`

So regardless if the dir was writable or not, the dmode set to 775 prevents the directory from actually being writable. It's stupid I didn't think of this before as I had a similar issue at work with an upload writable directory about a year ago and forgot.

So... Solution was to update to

`  config.vm.synced_folder "public_html", "/vagrant/public_html", :mount_options => ["dmode=777", "fmode=777"], :create => true`

Problem solved. Thanks for all the help, I really appreciate it.
