### ISSUE TITLE
I have set everything to do with fuel cms but login in to dashboard am still getting an error 404? why?

### ISSUE THREAD

**Issue by ckyate** [daylightstudio/FUEL-CMS#384]
I have entered my encryption key.
I have set ADMIN = true
Loaded DB schema
Set the db config file with mysql access
Double checked db config file
**But i still get page not found 404

**Comment by daylightstudio** [comment]
What about the .htaccess file?

**Comment by ckyate** [comment]
this is what i see in the .htaccess file; Deny from all
