### ISSUE TITLE
am getting a blank page or even sometimes i get an error 404 when i try to log into the dashboard

### ISSUE THREAD

**Issue by ckyate** [daylightstudio/FUEL-CMS#385]
This is what i get http://worldblogged.com/master/fuel/, yet i already asked here about the error and the admin told me about .htaccess files but one file has deny for all, Please i need help asap

**Comment by daylightstudio** [comment]
Since you are hosting it in a subfolder, the .htaccess found at the root of the site should be changed to the following:
```
RewriteBase /master/
```

**Comment by ckyate** [comment]
after adding RewriteBase /master/ to the .htaccess file it takes me to this page http://worldblogged.com/master/fuel/start and in the page am seeing 
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@worldblogged.kampala100.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

Apache Server at worldblogged.com Port 80

why am i seeing this, where is the error again??

**Comment by daylightstudio** [comment]
It sounds like it may be an issue with .htaccess and/or the mod_rewrite module not being installed on the server. One way to get around that would be to follow step 4 here:
http://docs.getfuelcms.com/installation/installing

**Comment by ckyate** [comment]
Perfect everything is working perfectly well but now i don't know how to make the front page and other pages am new to Fuel CM. 

Please i need help on how to style my website

**Comment by daylightstudio** [comment]
This may be a good place to start in the docs:
http://docs.getfuelcms.com/general/pages-variables

**Comment by ckyate** [comment]
i can see pages are already working e.g http://worldblogged.com/cms/icpau/about/Our-organisation. 
I have done what's in the doc but it gives me the same results as those pages i create in cms dashboard, how can i style my entire site and navigation
