### ISSUE TITLE
I don't know how to create the front and inside, and other widget pages in Fuel cms. I want to style my new website

### ISSUE THREAD

**Issue by ckyate** [daylightstudio/FUEL-CMS#386]
Perfect everything is working perfectly well after installing FUEL CMS but now i don't know how to make the front page and other pages am new to Fuel CM.

Please i need help on how to style my website

**Comment by daylightstudio** [comment]
You will want to style your pages probably by first modifying the assets/css/main.css file or use your own file and change the fuel/application/views/_blocks/header.php. In general, the HTML files will exist in the fuel/application/views/ for you to change.
