### ISSUE TITLE
I have done what's in the doc but it gives me the same results as those pages i create in cms dashboard, how can i style my entire site and navigation?

### ISSUE THREAD

**Issue by ckyate** [daylightstudio/FUEL-CMS#387]
i can see pages are already working e.g http://worldblogged.com/cms/icpau/about/Our-organisation. 
I have done what's in the doc but it gives me the same results as those pages i create in cms dashboard, how can i style my entire site and navigation?

**Comment by daylightstudio** [comment]
You will need to change the assets/css/main.css file and the view files found in fuel/application/views/ to style the site to your liking. I'd look at the fuel/application/views/_blocks/header.php and the fuel/application/views/_layouts/main.php in particular to get started.
