### ISSUE TITLE
404 error category page, and blog, user_guide module

### ISSUE THREAD

**Issue by Velbees12** [daylightstudio/FUEL-CMS#388]
404 error http://prntscr.com/dtv641 when I visit the website site.com/blog all I have done is set up a cms fuel, and installed according to instructions http://prntscr.com/dtv5x1, the module of the blog, please help to solve the problem and start the output. And please tell me, is there a standard design for this cms to see how to display information everywhere it is possible to do and tailor your design by analogy . Thanks in advance! The site is located on the hosting of all standard and customized according to your instructions 
 If you create a category in the admin center of such "news", and go to the site site.com/news also wrote 404
Work links only "pages" Do the links only pages http://prntscr.com/dtv7tj

**Comment by daylightstudio** [comment]
Try either updating to the develop branch of FUEL or read the following here to make the library, controller and model files lowercase (older syntax for CI 2.x):
https://github.com/daylightstudio/FUEL-CMS-Blog-Module/issues/23

**Comment by Velbees12** [comment]
Thank you, 404 error disappeared. Please tell me, I did according to the manual the output of blog articles on the home page, and there is such sample articles - how I can make that conclusion was based on category id? for example, where caregory_id=2

`<?php $posts = fuel_model('blog_posts', array('find' => 'all', 'limit' => 3, 'order' => 'sticky, date_added desc', 'module' => 'blog')) ?>`

**Thanks in advance for the help!**

**Comment by daylightstudio** [comment]
```
<?php $posts = fuel_model('blog_posts', array('find' => 'all', 'where' => array('category_id' => 2, 'limit' => 3, 'order' => 'sticky, date_added desc', 'module' => 'blog')) ?>
```
