### ISSUE TITLE
Call to undefined method Fuel_advanced_module::do_backup - help me please

### ISSUE THREAD

**Issue by Velbees12** [daylightstudio/FUEL-CMS#390]
I installed modules: FUEL-CMS-Backup-Module-master and google_analytics-master, to dashboard admin write error `Fatal error: Call to undefined method Fuel_advanced_module :: visits () in /var/www/site.com/ fuel / modules / google_analytics / controllers / dashboard.php on line 49` **and**  `Fatal error: Call to undefined method Fuel_advanced_module::do_backup() in /var/www/site.com/fuel/modules/backup/controllers/backup.php on line 65 ` 

Please help eliminate errors, thanks in advance!

**Comment by daylightstudio** [comment]
The Google Analytics module has been deprecated. Also, are you using the master branch (1.3.2 or the Develop branch 1.4)?

**Comment by Velbees12** [comment]
1.3.2 fuel cms, is it difficult to adapt the modules backup and analysts?
