### ISSUE TITLE
Changing url blog articles

### ISSUE THREAD

**Issue by Velbees12** [daylightstudio/FUEL-CMS#391]
Please tell me how can I change the address of the blog articles with `site.com/blog/2017/01/10/slugtest` change `site.com/name category article/slugtest`, that is to substitute the reference to the article's category is /blog/date. And remove the link `site.com/blog/categories/name` (viewing the category blog), change to `site.com/categoryname` . Thanks in advance for the help!

**Comment by daylightstudio** [comment]
It's not really possible to do that easily without changing some core code. Instead, you may want to look at creating some simple modules and using post pages that allow you to customize the routes:
http://docs.getfuelcms.com/modules/simple#post_pages
