### ISSUE TITLE
Automatic output of the categories in the menu

### ISSUE THREAD

**Issue by Velbees12** [daylightstudio/FUEL-CMS#392]
Wrote this conclusion the categories in the menu automatically:
```
<?php $posts = fuel_model('categories'); ?>
					<?php if (!empty($posts)) : ?>
<?php foreach($posts as $post) : ?>
<? $title = $post->name;?>
<? $url = $post->slug;?>
<? $nav[$title] = array('label' => $title, 'parent_id' => $title); ?>
<?php endforeach; ?>

<?php endif; ?>
```
How can you separate the main categories and their subcategories?(To display subcategories under their main categories)

**Thanks in advance for the help!**

**Comment by daylightstudio** [comment]
You can add a "where" parameter to your `fuel_model('categories', array('where' => array('parent_id' => 0)` to target the root category elements. If you use a "context" value in the admin, you can target that in the where condition as an alternative (e.g. `fuel_model('categories', array('where' => array('context' => '')`. Then while looping through the root categories, you can do a subsequent query to get all the child categories based on either their parent_id or a specified context value and do a nested loop through those.
