### ISSUE TITLE
where is the file for storing content of the page or post located?

### ISSUE THREAD

**Issue by ckyate** [daylightstudio/FUEL-CMS#393]
where is the file for storing content of the page or post located, because what i post in the page's body and post appears in the header section on the front end. Where is the file located to store the content in body ?

**Comment by daylightstudio** [comment]
If you are talking about creating a page from the Pages module, it will depend on the layout selected as to which view file it is tied to. By default, the file fuel/applications/views/_layouts/main.php is the file that is used. More on Layouts here:
http://docs.getfuelcms.com/general/layouts
