### ISSUE TITLE
where do i find the home page of my fuel cms website ?

### ISSUE THREAD

**Issue by ckyate** [daylightstudio/FUEL-CMS#394]
Dear Members where do i find the index file for my fuel cms (like this one i am working on http://worldblogged.com/cms/). i want to use it as my home page and to give it layouts, blocks and menus. so as to differentiate it from the inside pages.
Where should i find it in my folders to edit it's css?? help me please

**Comment by daylightstudio** [comment]
There is a fuel/application/views/_layouts/main.php file that holds the main HTML for that page which may reference a fuel/application/views/_blocks/header.php and fuel/application/views/_blocks/footer.php file as well.
