### ISSUE TITLE
i have made the home page but how do i differentiate the inside pages and create sidebars? 

### ISSUE THREAD

**Issue by ckyate** [daylightstudio/FUEL-CMS#395]
Now i have made the home page style http://worldblogged.com/cms/about%20us but it looks simillar to the inside pages like contact us and about us. 
So how do make different layouts for my inside pages to look totally different from the home pgae?
And how do i add left and right side bars in the pages?

thanks

**Comment by daylightstudio** [comment]
Here is some documentation on Layouts in FUEL:
http://docs.getfuelcms.com/general/layouts
