### ISSUE TITLE
Please help me i got error at first page. using xampp v3.2.2 php 7.1.1

### ISSUE THREAD

**Issue by FARIDUAN** [daylightstudio/FUEL-CMS#396]
**A PHP Error was encountered**
Severity: Warning

Message: Declaration of MX_Loader::library($library, $params = NULL, $object_name = NULL) should be compatible with CI_Loader::library($library = '', $params = NULL, $object_name = NULL)

Filename: MX/Loader.php

Line Number: 403

**A PHP Error was encountered**
Severity: Warning

Message: Declaration of MX_Loader::helper($helper) should be compatible with CI_Loader::helper($helpers = Array)

Filename: MX/Loader.php

Line Number: 0

**A PHP Error was encountered**
Severity: Warning

Message: Declaration of MX_Loader::helpers($helpers) should be compatible with CI_Loader::helpers($helpers = Array)

Filename: MX/Loader.php

Line Number: 0

**A PHP Error was encountered**
Severity: Warning

Message: Declaration of MX_Loader::language($langfile, $lang = '', $return = false) should be compatible with CI_Loader::language($file = Array, $lang = '')

Filename: MX/Loader.php

Line Number: 0

**A PHP Error was encountered**
Severity: Warning

Message: Declaration of MX_Loader::_ci_get_component($component) should be compatible with & CI_Loader::_ci_get_component($component)

Filename: MX/Loader.php

Line Number: 0

**A PHP Error was encountered**
Severity: Warning

Message: Declaration of MX_Lang::load($langfile, $lang = '', $return = false, $_module = NULL) should be compatible with CI_Lang::load($langfile = '', $idiom = '', $return = false, $add_suffix = true, $alt_path = '')

Filename: MX/Lang.php

Line Number: 94

**A PHP Error was encountered**
Severity: Notice

Message: Only variables should be assigned by reference

Filename: core/Loader.php

Line Number: 657

**A PHP Error was encountered**
Severity: 8192

Message: Methods with the same name as their class will not be constructors in a future version of PHP; Markdown_Parser has a deprecated constructor

Filename: helpers/markdown_helper.php

Line Number: 193

**A PHP Error was encountered**
Severity: Notice

Message: Array to string conversion

Filename: libraries/Fuel_navigation.php

Line Number: 248

**Comment by FARIDUAN** [comment]
I tried to access the admin, but redirect to the xampp dashboard

**Comment by daylightstudio** [comment]
What version of FUEL are you using (look at the fuel/modules/fuel/config/fuel_constants.php file)

**Comment by daylightstudio** [comment]
Closed due to inactivity
