### ISSUE TITLE
How to insert images like logo in my header getting them from the image folder of my website

### ISSUE THREAD

**Issue by ckyate** [daylightstudio/FUEL-CMS#397]
Dear members am at a stand still i want to insert my images in the header and home page of my website am developing which uses fuel cms, but have tried all avenues and i have failed.
this is my site: http://worldblogged.com/cms/

Please can someone send me sample codes on how to call those images from the image folder on my site to the header and home page body and other pages. 

i have read the documentation and no help in it.

**Comment by michaelumoren** [comment]
What code are you using to call/insert the image(s)?

**Comment by ckyate** [comment]
<img src="cpa logo.png" width="100" height="140">

**Comment by michaelumoren** [comment]
You didn't share your sample code.

To load an image from assets/images/image.png, use <img src="<?=img_path('image.png')?>">

Hope that helps.

**Comment by ckyate** [comment]
Thanks it has worked

**Comment by ckyate** [comment]
Now i need help to create blocks on my home page, i want to partition my home page with different blocks, i have created the blocks in my cms dashboard, but how should i display them on the home??

**Comment by daylightstudio** [comment]
If operating in the CMS inside say a textarea field, you can use `{fuel_block('block_name')}` using the templating syntax or you can use `<?=fuel_block('block_name')?>` in your layout view files.
