### ISSUE TITLE
fuel cms not working on php 7?

### ISSUE THREAD

**Issue by sohandhaindwal** [daylightstudio/FUEL-CMS#401]
Hi 
I am useing fuel cms in ubuntu 16 
Error list below when i render any page

A PHP Error was encountered

Severity: Warning

Message: Declaration of MX_Loader::library($library, $params = NULL, $object_name = NULL) should be compatible with CI_Loader::library($library = '', $params = NULL, $object_name = NULL)

Filename: MX/Loader.php

Line Number: 0
A PHP Error was encountered

Severity: Warning

Message: Declaration of MX_Loader::helper($helper) should be compatible with CI_Loader::helper($helpers = Array)

Filename: MX/Loader.php

Line Number: 0
A PHP Error was encountered

Severity: Warning

Message: Declaration of MX_Loader::helpers($helpers) should be compatible with CI_Loader::helpers($helpers = Array)

Filename: MX/Loader.php

Line Number: 0
A PHP Error was encountered

Severity: Warning

Message: Declaration of MX_Loader::language($langfile, $lang = '', $return = false) should be compatible with CI_Loader::language($file = Array, $lang = '')

Filename: MX/Loader.php

Line Number: 0
A PHP Error was encountered

Severity: Warning

Message: Declaration of MX_Loader::_ci_get_component($component) should be compatible with & CI_Loader::_ci_get_component($component)

Filename: MX/Loader.php

Line Number: 0
A PHP Error was encountered

Severity: Warning

Message: Declaration of MX_Lang::load($langfile, $lang = '', $return = false, $_module = NULL) should be compatible with CI_Lang::load($langfile = '', $idiom = '', $return = false, $add_suffix = true, $alt_path = '')

Filename: MX/Lang.php

Line Number: 0
A PHP Error was encountered

Severity: Notice

Message: Only variables should be assigned by reference

Filename: core/Loader.php

Line Number: 657
A PHP Error was encountered

Severity: Notice

Message: Array to string conversion

Filename: libraries/Fuel_navigation.php

Line Number: 248
Welcome to Fuel CMS
Version 1.3.2
Getting Started

    1
    Change the Apache .htaccess file

    Change the Apache .htaccess found at the root of FUEL CMS's installation folder to the proper RewriteBase directory. The default is your web server's root directory (e.g "/"), but if you have FUEL CMS installed in a sub folder, you will need to add the path to line 5. If you are using the folder it was zipped up in from GitHub, it would be RewriteBase /FUEL-CMS-master/.

    In some server environments, you may need to add a "?" after index.php in the .htaccess like so: RewriteRule .* index.php?/$0 [L]

    NOTE: This is the only step needed if you want to use FUEL without the CMS.
    2
    Install the database

    Install the FUEL CMS database by first creating the database in MySQL and then importing the fuel/install/fuel_schema.sql file. After creating the database, change the database configuration found in fuel/application/config/database.php to include your hostname (e.g. localhost), username, password and the database to match the new database you created.
    3
    Make folders writable

    Make the following folders writable (666 = rw-rw-rw, 777 = rwxrwxrwx, etc.):
        /var/www/html/FUEL-CMS-master/fuel/application/cache/
        (folder for holding cache files)
        /var/www/html/FUEL-CMS-master/fuel/application/cache/dwoo/
        (folder for holding template cache files)
        /var/www/html/FUEL-CMS-master/fuel/application/cache/dwoo/compiled
        (for writing compiled template files)
        /var/www/html/FUEL-CMS-master/assets/images
        (for managing image assets in the CMS)
    4
    Make configuration changes
        In the fuel/application/config/config.php, change the $config['encryption_key'] to your own unique key.
        In the fuel/application/config/MY_fuel.php file, change the $config['admin_enabled'] configuration property to TRUE. If you do not want the CMS accessible, leave it as FALSE.
        In the fuel/application/config/MY_fuel.php file, change the $config['fuel_mode'] configuration property to AUTO. This must be done only if you want to view pages created in the CMS.

That's it!

To access the FUEL admin, go to:
http://localhost/FUEL-CMS-master/fuel
User name: admin
Password: admin (you can and should change this password and admin user information after logging in)
What's Next?

    User Guide
    Visit the 1.0 user guide online
    Get rolling

    FUEL CMS is open source and on GitHub for a good reason. The communities involvement is an important part of it's success. If you have any ideas for improvement, or even better, a GitHub pull request, please let us know.
        Need help? Visit the FUEL CMS Forum.
        Found a bug? Report it on GitHub.
        Subscribe to our Twitter feed for FUEL CMS notifications.
        Visit our blog for tips and news.
        Visit our developer page for additional modules.

    To change the contents of this homepage, edit the fuel/application/views/home.php file.

    Happy coding!

    Home Features Developers Support Blog 

FUEL CMS is developed with love by Daylight Studio © 2017 Daylight Studio LLC, All Rights Reserved.

**Comment by daylightstudio** [comment]
Try the develop branch:
https://github.com/daylightstudio/FUEL-CMS/tree/develop
