### ISSUE TITLE
How to create a slider using featured images on posts of fuel cms?

### ISSUE THREAD

**Issue by ckyate** [daylightstudio/FUEL-CMS#402]
Please can anyone guide and help me on how to create a slider on my homepage for the pages i have created inside my CMS??
Need help?

**Comment by daylightstudio** [comment]
There are a number of ways to implement a slider so my answer will focus on just getting the featured images. Can you clarify how something is determined to be "featured"? Is it a simple module like "my_gallery" and the table behind it has a "featured" field. If so, you can use the following in your view:
```
<?php $featured = fuel_model('my_gallery', array('where' => array('featured' => 'yes'))) ?>;
```

**Comment by ckyate** [comment]
First of all where am i supposed to put the featured option on the page inside my dashboard and then where should i place this code you have given me ?

**Comment by daylightstudio** [comment]
What are you ultimately determining needs to be featured (e.g. a blog post, a news item, a career posting, etc)?

**Comment by ckyate** [comment]
News posting and blog posts but not pages

**Comment by ckyate** [comment]
yeah news items and blog posts plus careers this is my link http://worldblogged.com/cms/

**Comment by daylightstudio** [comment]
Have you looked into the documentation for creating a simple module. If not, I would start there. Here are some helpful link. You can think of simple modules as wrappers around your database tables. Closer to the bottom of the tutorial page it shows how it is used in a view file (e.g. /fuel/application/views/home.php)
http://docs.getfuelcms.com/modules/simple
http://docs.getfuelcms.com/modules/tutorial
