### ISSUE TITLE
installation  error occured

### ISSUE THREAD

**Issue by vkatariya** [daylightstudio/FUEL-CMS#406]
Hi  FUEL CMS Team,

I have installed fuel cms on my local system.
I followed the instruction for installation and click on the link 
http://localhost/FUEL-CMS-master/fuel/fuel/fuel

but redirect the phpmyadmin..

so  how to resolve this issue

**Comment by daylightstudio** [comment]
Was it installed in the subfolder of "FUEL-CMS-master"? If so, did you set the following in the .htaccess (around line 5):
```
RewriteBase /FUEL-CMS-master/
```
