### ISSUE TITLE
$key_field not working

### ISSUE THREAD

**Issue by besabellacyrus** [daylightstudio/FUEL-CMS#410]
Hospital_model
protected $key_field = 'hospital_id';

Doctors_model
public $has_many = array(
'hospitals' => array('hospitals_model'),
);

error
Unknown column 'slmc_hospitals.id' in 'where clause'

SELECT `slmc_hospitals`.* FROM `slmc_hospitals` WHERE `slmc_hospitals`.`id` IN(2) AND `slmc_hospitals`.`published` = 'yes'

What is wrong in my code, thank you.

**Comment by martynassateika** [comment]
I'm assuming `Hospital_model` is associated with the `slmc_hospitals` table. Does it have both a `hospital_id` and an `id` column?

**Comment by besabellacyrus** [comment]
yes its associated with slmc_hospitals. No just the hospital_id, anyways, i just changed hospital_id to just id.
what is the purpose of $key_field?

Thanks!

**Comment by daylightstudio** [comment]
Where are you seeing this in the application? In the admin edit screen or in your front end code?

**Comment by besabellacyrus** [comment]
in the front end.

**Comment by martynassateika** [comment]
@besabellacyrus The FuelCMS [documentation](http://docs.getfuelcms.com/libraries/my_model) has information about it.
> Usually the tables primary key(s)... can be an array if compound key

**Comment by daylightstudio** [comment]
How are you calling it on the front end?
