### ISSUE TITLE
Can't import database

### ISSUE THREAD

**Issue by nikhil167** [daylightstudio/FUEL-CMS#411]
Can't import the 'fuel_schema.sql'. it's loading and loading..
Nothing is happening? 
Help i'm a beginner
(phpmyadmin is working alright, i'm importing & Exporting other sql files.)

**Comment by daylightstudio** [comment]
I'm not able to replicate this issue. What version of phpMyAdmin are you using?

**Comment by nikhil167** [comment]
Thanks for Responding,
I am setting it on localhost using wamp.
phpMyAdmin version 4.6.4
Php 5.6

Looking forward for your Reply
Thanks.

**Comment by daylightstudio** [comment]
That is the same version I'm using. What if you just copy and paste it into the SQL command screen?

**Comment by nikhil167** [comment]
Thanks Mate,
That Worked.
