### ISSUE TITLE
I Want to transfer my website From a sub folder website to another folder website, but different servers

### ISSUE THREAD

**Issue by ckyate** [daylightstudio/FUEL-CMS#412]
I Want to transfer my website From a subfolder website to another folder website, but different servers
and to transfer from one subfolder where i developed it from to a main domain. i need help
see what i mean;
--- From this link http://worldblogged.com/cms to this link http://icpau.co.ug/ (subfolder to the main directory on different servers)

---From this link http://worldblogged.com/cms to this link http://icpau.co.ug/new (subfolder to subfolder on different servers)

**Comment by daylightstudio** [comment]
You will need to change your .htaccess "RewriteBase" on line 5 to juse `RewriteBase /` (and of course your database connection).
