### ISSUE TITLE
How can I change FuelCMS to German?

### ISSUE THREAD

**Issue by AlexL777** [daylightstudio/FUEL-CMS#413]
Hello Community,

I have the FuelCMS installed a while ago and am a German user. How can I install German language in the backend and frontend.

I have defined it in the fuel.php so, but in the backend the changes do not show.

```
|--------------------------------------------------------------------------
| Language settings
|--------------------------------------------------------------------------
*/

// Languages for pages. The key is saved to the page variables
$config['languages'] = array(
        'german' => 'German'
);

$config['settings'] = array();
$config['settings']['languages'] =  array(
                        'type' => 'keyval',
                        'fields' => array(
                                'key' => array('ignore_representative' => TRUE),
                                'label' => array('ignore_representative' => TRUE),
                            ),
                        'class' => 'repeatable',
                        'repeatable' => TRUE,
                        'ignore_representative' => TRUE
                    );

$this->fuel->language->set_selected('de');
```

What am I doing wrong?

Thanks in advance.

**Comment by incognitae** [comment]
hello,
    try
    
    $config['languages'] = array(
        'de' => 'German'
);
    
    Le 21/06/2017 à 08:51, Alexander
      Liebrecht a écrit :
    
    
      Hello Community,
      I have the FuelCMS installed a while ago and am a German user.
        How can I install German language in the backend and frontend.
      I have defined it in the fuel.php so, but in the backend the
        changes do not show.
      |--------------------------------------------------------------------------
| Language settings
|--------------------------------------------------------------------------
*/

// Languages for pages. The key is saved to the page variables
$config['languages'] = array(
        'german' => 'German'
);

$config['settings'] = array();
$config['settings']['languages'] =  array(
                        'type' => 'keyval',
                        'fields' => array(
                                'key' => array('ignore_representative' => TRUE),
                                'label' => array('ignore_representative' => TRUE),
                            ),
                        'class' => 'repeatable',
                        'repeatable' => TRUE,
                        'ignore_representative' => TRUE
                    );

$this->fuel->language->set_selected('de');

      What am I doing wrong?
      Thanks in advance.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/daylightstudio/FUEL-CMS","title":"daylightstudio/FUEL-CMS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/daylightstudio/FUEL-CMS"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"How can I change FuelCMS to German? (#413)"}],"action":{"name":"View Issue","url":"https://github.com/daylightstudio/FUEL-CMS/issues/413"}}}
    
    
    --

**Comment by AlexL777** [comment]
Thanks for the tip, but unfortunately no success.

I have inserted the code in the fuel.php. What can it be?

In the backend no changes and in the backend there is no option to change the language directly.

**Comment by incognitae** [comment]
in MY_fuel.php , i put for my own use in french :
    // languages for pages. The key is saved to the page variables
      $config['languages'] = array(
          'fr' => 'french',
      );
      // The default language to use
      $config['language_default_option'] = 'fr';
    
    
    Check if you have directory German in all your language directory
      in fuel, codeigniter directories and in your application directory
      too
    
    Any error message ?
    
    
    Le 21/06/2017 à 10:17, Alexander
      Liebrecht a écrit :
    
    
      Thanks for the tip, but unfortunately no success.
      I have inserted the code in the fuel.php. What can it be?
      In the backend no changes and in the backend there is no option
        to change the language directly.
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/daylightstudio/FUEL-CMS","title":"daylightstudio/FUEL-CMS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/daylightstudio/FUEL-CMS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AlexL777 in #413: Thanks for the tip, but unfortunately no success.\r\n\r\nI have inserted the code in the fuel.php. What can it be?\r\n\r\nIn the backend no changes and in the backend there is no option to change the language directly."}],"action":{"name":"View Issue","url":"https://github.com/daylightstudio/FUEL-CMS/issues/413#issuecomment-310002018"}}}
    
    
    --

**Comment by daylightstudio** [comment]
The backend and frontend are handled differently. The backend is handled with a language file that should be placed in the fuel/modules/fuel/language/german folder and then you should specify "german" as the language in the fuel/application/config.php file (not the MY_fuel.php). The current german language version is out of date though and needs some german speakers to update it :)
https://github.com/daylightstudio/FUEL-CMS-Languages/tree/master/modules/fuel/language/german

The frontend is controlled by FUEL's language feature:
http://docs.getfuelcms.com/general/localization
