### ISSUE TITLE
I'm unable to access my Fuel CMS account

### ISSUE THREAD

**Issue by Diablo1066** [daylightstudio/FUEL-CMS#414]
When trying to load the site I'm receiving numerous Errors and exceptions.

**Comment by michaelumoren** [comment]
Can you share the errors you are getting?

**Comment by Diablo1066** [comment]
Sure 

An uncaught Exception was encountered

Type: Exception

Message: Session: Configured save path '/home/domains/vol2/228/1294228/user/htdocs/fuel/application/cache/sessions' is not writable by the PHP process.

Filename: /home/domains/vol2/228/1294228/user/htdocs/fuel/codeigniter/libraries/Session/drivers/Session_files_driver.php

Line Number: 143

Backtrace:

File: /home/domains/vol2/228/1294228/user/htdocs/fuel/modules/fuel/core/Loader.php
Line: 791
Function: __construct

File: /home/domains/vol2/228/1294228/user/htdocs/fuel/modules/fuel/core/Loader.php
Line: 684
Function: _ci_init_library

File: /home/domains/vol2/228/1294228/user/htdocs/fuel/modules/fuel/core/Loader.php
Line: 538
Function: _ci_load_stock_library

File: /home/domains/vol2/228/1294228/user/htdocs/fuel/modules/fuel/core/Loader.php
Line: 592
Function: _ci_load_library

File: /home/domains/vol2/228/1294228/user/htdocs/fuel/modules/fuel/core/Loader.php
Line: 198
Function: _ci_load_library

File: /home/domains/vol2/228/1294228/user/htdocs/fuel/modules/fuel/core/Loader.php
Line: 215
Function: library

File: /home/domains/vol2/228/1294228/user/htdocs/fuel/modules/fuel/core/Loader.php
Line: 171
Function: libraries

File: /home/domains/vol2/228/1294228/user/htdocs/fuel/modules/fuel/core/Loader.php
Line: 95
Function: initialize

File: /home/domains/vol2/228/1294228/user/htdocs/fuel/modules/fuel/controllers/Page_router.php
Line: 10
Function: __construct

File: /home/domains/vol2/228/1294228/user/htdocs/index.php
Line: 371
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: fopen(q2uk0e5vocgptk409co57htpnmtkjqbu): failed to open stream: Permission denied

Filename: drivers/Session_files_driver.php

Line Number: 172

Backtrace:

A PHP Error was encountered

Severity: Warning

Message: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/home/domains/vol2/228/1294228/user/htdocs/fuel/application/cache/sessions)

Filename: Unknown

Line Number: 0

Backtrace:

**Comment by michaelumoren** [comment]
Looks like a file permission issue.. Are you able to load the FUEL CMS welcome page without any errors?

**Comment by Diablo1066** [comment]
I can access the general Fuel CMS website but not ours sitting on the CMS - there are no hosting issues

**Comment by michaelumoren** [comment]
I didn't mean the general FUEL website. I meant yours. When you install and start using the CMS, there's a default welcome page. My question is, are you able to access this page?

Also, can you update your config to save sessions to the database instead of file, just to test?

**Comment by Diablo1066** [comment]
No sorry i can't, let me see if i can make the changes now to test

**Comment by daylightstudio** [comment]
Closed due to inactivity.
