### ISSUE TITLE
Edit modal empty when a module is not defined

### ISSUE THREAD

**Issue by wedumatt** [daylightstudio/FUEL-CMS#416]
I'm working on a site that uses Fuel CMS and discovered a difficult to track down bug.

When I click on the edit button in the admin panel:

![edit1](https://user-images.githubusercontent.com/30811068/29222734-c209e37a-7e91-11e7-85b6-e1688a428d12.png)

It only shows a small portion of a static header image. The rest of the response is blank. The browser inspector shows that there is a 404 error while fetching the page `/admin/undefined/inline_edit/1`. The `undefined` is from the lack of a `data-module` attribute.
dd
![edit2](https://user-images.githubusercontent.com/30811068/29222749-cedba232-7e91-11e7-86bc-3b7ea188f5af.png)

So it took a lot of digging through source code but I discovered the reason for the 404, and `undefined` in the URL path was because the file `application/config/MY_fuel_modules.php` was missing a module definition:

```php
$config['modules']['campaign_toolkit_categories'] = array(
	'module_name' => 'Campaign Toolkit Categories'
);
```

I think when rendering the modal window it would be useful to display an error message when this happens. Best of course if it can specify the real problem ("module name is undefined" or something) but even a simple "resource failed to load" would be better than showing what looks like a block that may have failed to render or has bad CSS that sets the height very small.

Thank you for your consideration of this issue.

**Comment by daylightstudio** [comment]
Try pulling from the develop branch to see if this issue is fixed for you.
