### ISSUE TITLE
Cannot access admin login page.

### ISSUE THREAD

**Issue by git-vik** [daylightstudio/FUEL-CMS#418]
I have installed fuel cms on my local system.
i have installed fuelcms on http://localhost/fuelcms/ and trying to access admin login from http://localhost/fuelcms/login
I followed the instruction for installation and click on the link for admin panel. But it redirects me to http://localhost/dashboard page

**Comment by daylightstudio** [comment]
You need to alter the .htaccess file (step 4 in link below) to `RewriteBase /fuelcms/`:
http://docs.getfuelcms.com/installation/installing

**Comment by git-vik** [comment]
Thanks it is working now.
