### ISSUE TITLE
After clean-install login/pw admin/admin says 'invalid login' 

### ISSUE THREAD

**Issue by strahlenroboter** [daylightstudio/FUEL-CMS#419]
I set up FUEL-CMS-master.zip from github (version 1.4), followed all the installations instructions but accessing the admin-page is not possible due to some kind of login-error (HOSTNAME/fuel-1.4.0/fuel/login/5a6e566c6243396b59584e6f596d3968636d513d). Can't find out why.

On the html-page it says: invalid login.

I've set $config['uri_protocol'] = 'QUERY_STRING'; according to http://forum.getfuelcms.com/discussion/1613/first-time-login-fail-/p1

But no effects. I've tried to get an account at http://forum.getfuelcms.com/entry/register but my 'humanity' seems suppicous. I wouldn't doubt that. At least I don't get a login there. What a pity!

Also there's some minor errors on some php functions (behind the html)... Are they more than minor? Don't know...

Thanks for helping!

<h4>A PHP Error was encountered</h4>
--
  |  
  | <p>Severity: Warning</p>
  | <p>Message:  preg_replace_callback() [<a href='function.preg-replace-callback'>function.preg-replace-callback</a>]: Compilation failed: unrecognized character after (?&lt; at offset 5</p>
  | <p>Filename: core/Security.php</p>
  | <p>Line Number: 522</p>
  |  
  |  
  | <p>Backtrace:</p>
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  | <p style="margin-left:10px">
  | File: /home/luc/www/fuel-1.4.0/fuel/modules/fuel/controllers/Login.php<br />
  | Line: 81<br />
  | Function: post			</p>
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  | <p style="margin-left:10px">
  | File: /home/luc/www/fuel-1.4.0/index.php<br />
  | Line: 364<br />
  | Function: require_once			</p>
  |  
  |  
  |  
  |  
  | </div>
  | <div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
  |  
  | <h4>A PHP Error was encountered</h4>
  |  
  | <p>Severity: Warning</p>
  | <p>Message:  preg_replace_callback() [<a href='function.preg-replace-callback'>function.preg-replace-callback</a>]: Compilation failed: unrecognized character after (?&lt; at offset 5</p>
  | <p>Filename: core/Security.php</p>
  | <p>Line Number: 522</p>
  |  
  |  
  | <p>Backtrace:</p>
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  | <p style="margin-left:10px">
  | File: /home/luc/www/fuel-1.4.0/fuel/modules/fuel/controllers/Login.php<br />
  | Line: 81<br />
  | Function: post			</p>
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  | <p style="margin-left:10px">
  | File: /home/luc/www/fuel-1.4.0/index.php<br />
  | Line: 364<br />
  | Function: require_once			</p>
  |  
  |  
  |

**Comment by daylightstudio** [comment]
That compilation error is coming from the xss_clean function in CodeIgniter. Are you using the default "admin"/"admin" login or do you have your own login and password. Also, what version of PHP are you using?

**Comment by strahlenroboter** [comment]
I'm using admin/admin as mentioned in the install instructions. It's Php version 5.3.3


Thanks!

Am 6. September 2017 18:33:26 MESZ schrieb David McReynolds <notifications@github.com>:
>That compilation error is coming from the xss_clean function in
>CodeIgniter. Are you using the default "admin"/"admin" login or do you
>have your own login and password. Also, what version of PHP are you
>using?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/daylightstudio/FUEL-CMS/issues/419#issuecomment-327540778

-- 
This message was sent from a smartphone.

**Comment by strahlenroboter** [comment]
Hi there again, I'd really love to try out your CMS but the mentionned errors are preventing me from it. Could you actually help me to make the login work. It seems that I followed the instructions precisely... That'd be great, because your CMS (besides these issues) seem to be the right approach!

Thank you!

**Comment by daylightstudio** [comment]
Do you have access to a newer version of PHP by chance? The php requirements should actually be 5.3.7 and not 5.2 as stated in the docs. I've updated it to 5.4 just in case.

**Comment by strahlenroboter** [comment]
Well, I check with the provider. Thanks! Hope the problem is gonna be solved then.
