### ISSUE TITLE
use of eval

### ISSUE THREAD

**Issue by mkannan22** [daylightstudio/FUEL-CMS#423]
Would anyone be able to explain why or why not the eval function is potentially vulnerable inside of loader.php? Specifically on line 392. Also, same question for compatibility_helper.php on line 136.

**Comment by daylightstudio** [comment]
For the loader, that is specifically for older versions of PHP that don't support the "short_open_tag" and is something found in the core CI Loader file as well. The compatability_helper.php is for really old versions of PHP that don't support json_decode.

**Comment by mkannan22** [comment]
Thanks for the response. I believe this may be a security vulnerability.
