### ISSUE TITLE
 A PHP Error was encountered on my website for fuel http://bigdrumcapital.com/cms

### ISSUE THREAD

**Issue by ckyate** [daylightstudio/FUEL-CMS#424]
A PHP Error was encountered

Severity: Notice

Message: Only variables should be passed by reference

Filename: _layouts/main.php

Line Number: 46

see the code below
<?php $this->load->view('_blocks/header')?>
  <main class="container">
     <?php /* BREADCRUMBS */ ?>
     <?php if(!is_home()): ?>
     <div class="breadcrumbs">
     	<?php echo fuel_nav(array('render_type' => 'breadcrumb')); ?>
     </div>
     <?php endif; ?>
    <?php /* RIGHT SIDE WITH SIDE MENU AND BLCOKS */ ?>
    <?php if (!empty($blocks) OR !empty($sidemenu)) : ?>

        <?php if (!empty($sidemenu)) : ?>
        <div  class="left-sidemenu">
        <?php echo $sidemenu; ?>
        </div>
        <?php endif ?>
 
        <?php if (!empty($blocks)) : ?>
        <div id="blocks">
            <?php foreach($blocks as $block) : ?>
 
                <div class="block">
                <?php echo fuel_block($block); ?>
                </div>
 
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
 
    <?php endif; ?>
 

    <div class="main <?php echo !empty($sidemenu) ? "has-sidemenu" : "" ?>">
    	<?php if ( !empty($featured_image) && !is_home() ): ?>
    		<?php // print_r(fuel_model('fuel_pagevariables', array('find' => 'all')));?>
    		<div class="featured-image">
    			<img src="<?php echo img_path(fuel_var('featured_image'))?>" />
    		</div>
    	<?php endif; ?>
    	
    	<?php if( !is_home() ): ?>
    	<h1><?php echo fuel_var('page_title'); ?></h1>
        <?php endif; ?>
        <?php
		$cur_url = current_url();
		$slug = end(explode('/', $cur_url));

		$resources = $category = $this->fuel->categories->find_by_slug($slug);
	?>
	
        <div class="main-body<?= !empty($resources) ? ' has-resources' : '' ?>">
        <?php echo fuel_var('body', ''); ?>
        </div>
        <?php echo fuel_block('pdf-right'); ?>
        
        <?php echo fuel_block('pdf-display'); ?>
             
        <?php
        	if(!empty($related_pages)){
        		echo '<div class="related-pages">';
        		echo '<h3>Related Pages</h3>';
        		echo $related_pages;
        		echo '</div>';
        	}
        ?>
  
  </main>
    <div class="clear"></div>
 
  
 <?php $this->load->view('_blocks/footer')?>

where should i fix to sort my main ?

**Comment by daylightstudio** [comment]
That's a PHP version issue. Which version of PHP are you using?
