### ISSUE TITLE
I can't access my fuel dashboard and am seeing this error below;  What should i do? 

### ISSUE THREAD

**Issue by ckyate** [daylightstudio/FUEL-CMS#425]
Not Found

The requested URL /fuel/start was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Apache Server at bigdrumcapital.com Port 80

**Comment by daylightstudio** [comment]
Do you have .htaccess enabled for your server? Also, see if this helps:
https://www.codeigniter.com/user_guide/installation/troubleshooting.html

**Comment by ckyate** [comment]
Yeah i have the .htaccess file and also tried the link above you provided by $config['index_page'] = "index.php";
To this:

$config['index_page'] = "index.php?"; but nothing changes

**Comment by ckyate** [comment]
i have fixed it

**Comment by graceryfolad** [comment]
i am also have the same issue here, http://localhost:8056/fuelcms/index.php/fuel is not working.

**Comment by martynassateika** [comment]
@ckyate Could you share what was wrong? Might help other people :-)

**Comment by graceryfolad** [comment]
the installation is working fine now, i just change to the right url in the config.php file of fuel directory

**Comment by rajeev1690** [comment]
**I am getting this error**

Object not found!
The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.

Error 404
localhost
Apache/2.4.26 (Win32) OpenSSL/1.0.2l PHP/7.1.7
