### ISSUE TITLE
Why the recapcha is so hard to understand?

### ISSUE THREAD

**Issue by hahadaba** [daylightstudio/FUEL-CMS#429]
I tried to apply a membership of your forum,but I failed 100 times in typing the recapcha string.I am not a robot at all.
In fact I want to ask  if there is some easy step-to-step guide to use fuelcms,for example,after I create one page on the dashboard,how can I set it as homepage?
I did not find answers yet.

**Comment by daylightstudio** [comment]
If you create a page with the location of "home", it will become your homepage.

Additionally, here are some of the more commonly visited pages in the docs:
http://docs.getfuelcms.com/general/pages-variables
http://docs.getfuelcms.com/modules/tutorial
http://docs.getfuelcms.com/general/forms

We'll have to take a look at the issue with the forum.
