### ISSUE TITLE
Fuel_installer.copy_config does not copy configuration file

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS#431]
Due to an empty `if` statement in the `copy_config` method, the configuration file is never actually copied.

I'd suggest not using the 'at' symbol next to copy, as we're masking errors. Instead copy the result of the `copy` call into a variable, and add an error using `$this->_add_error` if the copy fails.

https://github.com/daylightstudio/FUEL-CMS/blob/develop/fuel/modules/fuel/libraries/Fuel_installer.php#L724

Besides, this is `Fuel_installer`, meaning it's only called during development. We **want** devs to know the copy failed :-)

**Comment by daylightstudio** [comment]
I'm not quite sure I understand what you mean by an empty `if` statement.

**Comment by martynassateika** [comment]
Oh oops, I was actually wrong. It's not that it *never* copies the file, it seems it *always* tries to call `copy`.

> I'm not quite sure I understand what you mean by an empty if statement.

Look at the end of the `if`. There's a semi-colon, meaning the `if` does nothing.

**Comment by daylightstudio** [comment]
Ah... I see now. So something like this is what you are suggesting?
```
public function copy_config()
{
	$source_path = $this->install_path().'../config/'.$this->module.'.php';
	$dest_path = APPPATH.'config/'.$this->module.'.php';

	if (file_exists($source_path) AND !file_exists($dest_path))
	{
		$results = copy($source_path, $dest_path);

		if (!$results)
		{
			$this->_add_error(lang('error_could_not_create_file', $dest_path));
		}
	}
}
```

**Comment by martynassateika** [comment]
Yup! Then the `install` function will return `FALSE` rather than `TRUE`.

**Comment by daylightstudio** [comment]
Thanks. A fix has been pushed to the develop branch.

**Comment by martynassateika** [comment]
No worries. Thanks for replying so quickly on a Sunday! It wasn't really urgent :-P

**Comment by daylightstudio** [comment]
No problem... was working on FUEL stuff anyway.
