### ISSUE TITLE
CodeIgniter 3.1.7 released

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS#433]
A new version of CI was released yesterday:
https://www.codeigniter.com/userguide3/changelog.html#version-3-1-7

Some database related bug-fixes, so would be good to have them in.

**Comment by martynassateika** [comment]
By the way, it seems the `composer.json` file still uses the server requirements of CI 3.0.
As of now CI recommends PHP 5.6 and up. https://www.codeigniter.com/user_guide/general/requirements.html

Are there plans to update the server requirements of FUEL as well? 5.6 will stop receiving security updates at the end of this year! http://php.net/supported-versions.php

**Comment by daylightstudio** [comment]
Version 1.4.2 was released that has the 3.1.7.
