### ISSUE TITLE
It looks like the Autoloader.php path on Fuel_twig_parser.php is not correct

### ISSUE THREAD

**Issue by watahell** [daylightstudio/FUEL-CMS#434]
Hi there

I had a hard time making my new installation work. Apparently the following file needs a fix:
/fuel/modules/fuel/libraries/parser/Fuel_twig_parser.php

On Line 29, it has the following line:
require_once(FUEL_PATH . 'libraries/parser/twig/Autoloader.php');

But it should be:
require_once(FUEL_PATH . 'libraries/parser/Twig/Autoloader.php');

After fixing that, my installation works fine.

Thanks
Marcos

**Comment by daylightstudio** [comment]
Thanks for the report. That should be fixed now.
