### ISSUE TITLE
forum.getfuelcms.com is inaccessible

### ISSUE THREAD

**Issue by dgvirtual** [daylightstudio/FUEL-CMS#438]
For a few days at least

**Comment by daylightstudio** [comment]
Are you seeing any errors or could you better explain what you are experiencing? I've been answering forum threads the last couple days. What's your user handle?

**Comment by martynassateika** [comment]
Is it the mobile site you're talking about @dgvirtual? I couldn't ever access it, always had to load the desktop version on my phone.

**Comment by dgvirtual** [comment]
I see now that I cannot access the forum only on my phone (Firefox for Android or Chrome for Android). But the url is the same as on the desktop (forum.getfuelcms.com), so I have no clue on how to "load the desktop version" on the phone. 

The "error message" says "Bonk. something funky happened. Please bear with us while we iron out the kinks."
 here is a link to a screenshot: 
https://mega.nz/#!wlFFGQ6T!Fldi6Yd3Zz28YMTJrfUxvIJw_n4kmf7vdFLRhmujZQ4

The main getfuelcms.com site and docs are accessible (though docs are not very fun to read on mobile phone). 

And, btw, Sveikas Martynai :)

**Comment by martynassateika** [comment]
Labas!

As a workaround you can just tap on the menu icon in the top right (three dots) and select "Request desktop site".

But yes it's really weird how it loads something completely different on mobile. Fixing this would help users get FuelCMS help quicker.

**Comment by dgvirtual** [comment]
Yeh @martynassateika , how could I have missed that mobile browser option, I had seen it before, although never used it much. 

Perhaps, as a workaround, the error message could be amended to include the suggestion to try to load the desktop site? As for me, the issue can be closed.
