### ISSUE TITLE
span tag not assigned to anything in Fuel_custom_fields

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS#444]
See line: https://github.com/daylightstudio/FUEL-CMS/blob/develop/fuel/modules/fuel/libraries/Fuel_custom_fields.php#L1648

Looks like it should be appended to `$str`?

**Comment by martynassateika** [comment]
Hey, thanks for the fix. It seems you accidentally appended `$str .= ` to the return value, too, though!

**Comment by daylightstudio** [comment]
Going to fast on my end... try now.

**Comment by martynassateika** [comment]
Looks good, thanks!
