### ISSUE TITLE
MY_date_helper calls non-existent function 'convert_date_to_array'

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS#453]
https://github.com/daylightstudio/FUEL-CMS/blob/58c0fc11f112628ef2c9f553cb5583bff0c2b866/fuel/modules/fuel/helpers/MY_date_helper.php#L335

Couldn't find this function anywhere in FUEL CMS or in the PHP docs.

**Comment by daylightstudio** [comment]
I think it is meant to be the "date_parse" function.

**Comment by martynassateika** [comment]
There are still some issues with this function.

Try:

```php
$this->load->helper('my_date');
var_dump(format_db_date('2016-09-05 10:30:05'));
```

The array returned by `date_parse` contains the [following keys](http://php.net/manual/en/function.date-parse.php):

```
array (size=12)
  'year' => int 2016
  'month' => int 9
  'day' => int 5
  'hour' => int 10
  'minute' => int 30
  'second' => int 5
  'fraction' => float 0
  'warning_count' => int 0
  'warnings' => 
    array (size=0)
      empty
  'error_count' => int 0
  'errors' => 
    array (size=0)
      empty
  'is_localtime' => boolean false
```

Note how FUEL CMS expects `min` and `sec`, yet `minute` and `second` are returned, respectively.
