### ISSUE TITLE
'null' displayed instead of error message 'error_class_property_does_not_exist'

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS#456]
To reproduce, call:

```php
class Site extends CI_Controller
{
	function index()
	{
		$this->fuel->blah();
	}
}
```

Error:

```
An uncaught Exception was encountered
Type: Exception
Message: (null)
Filename: C:\wamp64\www\FUEL-CMS\fuel\modules\fuel\libraries\Fuel.php
Line Number: 506
```

Looks like `MY_language_helper` cannot find the key 'error_class_property_does_not_exist'.

**Comment by daylightstudio** [comment]
It looks like the language files only get loaded if you are in the admin. Does adding this to the file fix it on line 507 of Fuel.php?
```
$this->load_language('fuel', 'fuel');
```

**Comment by martynassateika** [comment]
Yup! If I have

```php
$this->load_language('fuel', 'english');
throw new Exception(lang('error_class_property_does_not_exist', $var));
```

I get the correct error message:

```
An uncaught Exception was encountered
Type: Exception
Message: Class property blah does not exist
Filename: C:\wamp64\www\FUEL-CMSa\fuel\modules\fuel\libraries\Fuel.php
Line Number: 507
```

**Comment by martynassateika** [comment]
Oof, parameter 2 is language, so you'd need something like

```php
$this->load_language('fuel', 'english');
```

Something similar is done in `Fuel_advanced_module`, no?

https://github.com/daylightstudio/FUEL-CMS/blob/58c0fc11f112628ef2c9f553cb5583bff0c2b866/fuel/modules/fuel/libraries/Fuel_advanced_module.php#L79-L86

Wonder if there's a way to make both modules go via the same code path.

**Comment by martynassateika** [comment]
There's a nice way to solve this.

In `Fuel::initialize`, you can just call

```php
parent::initialize($config);
```

It'll then load the language in `Fuel_advanced_module::initialize`.

Does that look ok?

**Comment by daylightstudio** [comment]
That will actually cause an error because the Fuel_base_library which the Fuel_advanced_module inherits from has a _check_permissions() method in the initialize method on it that requires the fuel object to already be loaded on the module (which is essentially $this)... and the _check_permissions isn't necessary to be called for the Fuel module.

**Comment by martynassateika** [comment]
Ahh okay. It just feels like it'd be easy to miss adding those `$this->load_language` calls :-/

Are the methods in the `Fuel` class supposed to require any special permissions to run?

**Comment by daylightstudio** [comment]
There currently aren't any special permissions for the FUEL object to be run.

**Comment by martynassateika** [comment]
I just noticed that `Fuel_base_library` itself does not require any special permissions (the `$permission` field is set to `''`). Since the `Fuel` class doesn't override that, wouldn't it be safe?

**Comment by martynassateika** [comment]
Oh wait nevermind, I didn't read that right initially. `Fuel_base_library::initialize` basically requires a fully built `Fuel` object, yup?

Yeah in that case with the current class hierarchy it might be tricky to load the language files safely alongside :-)
