### ISSUE TITLE
Compatibility helper serves little purpose given current server requirements

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS#461]
The `compatibility_helper` file has a number of functions that provide functionality for people using old versions of PHP.

FUEL CMS requires PHP 5.4+, which means all the functions in that file (except `str_putcsv`!) are already available out-of-the-box.

IMO we should get rid of those functions. If I understand correctly for people with 5.4+ the `function_exists` checks would all return `FALSE` anyway, right? In which case it's pretty much dead code :-)

**Comment by daylightstudio** [comment]
That's correct... most of those functions are not needed and should be removed.
