### ISSUE TITLE
read_file result unused in Pages

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS#463]
https://github.com/daylightstudio/FUEL-CMS/blob/58c0fc11f112628ef2c9f553cb5583bff0c2b866/fuel/modules/fuel/controllers/Pages.php#L1058

The `read_file` function is called (which is now deprecated, by the way!), but the result isn't used at all. Is it supposed to be used? Or can we skip reading the file entirely?

**Comment by daylightstudio** [comment]
I believe that code was offloaded to the Fuel_pages::import method and is no longer needed.
