### ISSUE TITLE
fuel_vars not working in fuel blocks

### ISSUE THREAD

**Issue by ateebahmed** [daylightstudio/FUEL-CMS#467]
Hello I have an issue regarding using fuel cms blocks which I was going to post on forums but their mail is not working or I was not able to receive any confirmation email, due to this I am asking here.
I am using a fuel block to render it in my page through cms and I saw that you can pass variables to it. But I cannot access them in my block, when I use `fuel_var` to access the value, it does not return or returns a default value if I provide it one. Please confirm how can I access the vars in my blocks?
**In fuel cms**
**page**
`{fuel_block(array(
            'view' => 'nt_project_card',
            'vars' => array(
                'project_title' => 'Test Project',
                'project_desc' => 'Some details about project',
                'project_link' => 'projects/project1'
            )))}
`
**block**
`
<img class="card-img-top" src="{fuel_var('img')}" alt="Project Image">
    <div class="card-body">
        <h5 class="card-title">{fuel_var('project_title', 'Title')}</h5>
        <p class="card-text">{fuel_var('project_desc')}</p>
        <a href="{site_url(fuel_var('project_link'))}" class="btn btn-link">Read More...</a>
    </div>
`

**Comment by martynassateika** [comment]
Instead of using `fuel_var`, try accessing variables in the block directly, e.g. `$project_title`.

**Comment by ateebahmed** [comment]
already tried doing it
`$project_title` and `{project_title}`
it throws error saying undefined variable

**Comment by daylightstudio** [comment]
There seemed to be an issue with the Fuel_block library in retrieving the view variable from the database which automatically get's parsed. In this case, you don't want it automatically parsed but instead the raw "view" value which then gets parsed in the Fuel_block::render method. I've posted a fix in the develop branch.

**Comment by ateebahmed** [comment]
should I pull from develop branch for this fix right now? I need to implement it in soon to be production code

**Comment by daylightstudio** [comment]
Yes.

**Comment by ateebahmed** [comment]
Thank you to both of you. The fix worked like a charm and I was able to access my variables inside block. I think this should also be added in documentation.
Define block in page like this
`{fuel_block(array('view' => 'my_view', 'vars' => array('var1' => 'var1_value'...)))}`
and access variables in block like this
`{$var1}...`

**Comment by ateebahmed** [comment]
Hi again! I was using this block for few things and I noticed that if I were to use a script tag in this block then the variables are not rendered.
**Example**
`<script>
$(function () {
$({$class}).(someaction)
})</script>`

The `$class` var is rendered as it is in the final code, but if you use it outside of script tag in same block then it will render fine.
So I was thinking if we could use it for script tag as well or there is some security related issue while saving or rendering the js script?

**Comment by daylightstudio** [comment]
There is a template filter that will add spaces after a before `{ ` and ` }` within javascript code to prevent template parsing errors. By adding the spaces, it disables the template parsing. So in short, you currently can't embed variables within script tags. Instead, you can simply use normal PHP code`<?=$class?>`.

**Comment by daylightstudio** [comment]
Actually, your `<script>` block is in the CMS correct? If so, then you can't merge variables in it using normal PHP code. The templating syntax was meant mostly for form inputs in the CMS. The usage of normal PHP code only works with static block view files.
