### ISSUE TITLE
Asset Cachebusting/Timestamp

### ISSUE THREAD

**Issue by marcus-at-localhorst** [daylightstudio/FUEL-CMS#477]
I can't find the place where `public $assets_last_updated` ever gets the real file modification time. Therefore the param xxx.js?c= never has an value. Why is that? I need the cache busting param, but not the fuel cms caching. But even there, it is not working:
`$cache_file_name = $cache_file_name_md5.'_'.strtotime($this->assets_last_updated).'.'.$ext;` results in `"/assets/cache/31da0f767fa48d924f5aa376b0c3d70a_.js"`

Any idea?

**Comment by daylightstudio** [comment]
It's loaded in the fuel/assets/config/asset.php file that has the `$config['assets_last_updated']` (CI will automatically load in a config that's the same name as the class). The date in the config needs to be updated.

**Comment by marcus-at-localhorst** [comment]
Oh, I see. I thought it's fully automatic with `filemtime()`. 
Thanks.
