### ISSUE TITLE
Only last advanced module added to 'modules_allowed' array in \Generate::advanced

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS#496]
Add multiple modules at once via the CLI:

`php index.php fuel/generate/advanced a:b:c`

**Expected:**

All modules to be added to the 'modules_allowed' config:

```php
$config['modules_allowed'] = array(
    // previous ...
    'a',
    'b',
    'c'
);
```

**Actual:**

Only the last module is added:

```php
$config['modules_allowed'] = array(
    // previous ...
    'c'
);
```

**Comment by daylightstudio** [comment]
I believe the multiple generation only works for models and not advanced modules.

**Comment by martynassateika** [comment]
Ah yes, my bad, just double checked the documentation.

The thing is though, all 3 methods call `_get_module_names` which splits the supplied name at `:`.

Fuel CMS is *really* close to supporting multiple module creation, it looks like the permissions is the only issue!

I think we should either:
* prevent multi-module instantiation by calling `_get_module_names` and showing an error if the length of the returned array is not equal to 1, or
* collect the advanced module names in advance, and then make all changes to the 'modules_allowed' array in one go.

**Comment by martynassateika** [comment]
Actually it's fully possible to generate multiple simple modules without issues (`a:b:c`). Maybe the documentation should be updated?
