### ISSUE TITLE
Suspicious calls to \Fuel_redirects::add

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS#513]
I might be wrong but the two calls to `add` in `\Fuel_redirects::redirects` seem a bit suspicious:
```php
if (isset($config['passive_redirects']) AND $only_passive)
{
	// merge variable $redirects with passive redirects for compatibility with older version
	$this->add($config['passive_redirects'], TRUE);
	return $this->passive_redirects;
}
else if (isset($config['aggressive_redirects']) AND !$only_passive)
{
	$this->add($config['aggressive_redirects'], FALSE);
	return $this->aggressive_redirects;
}
```
As you can see there are two arguments passed to `$this->add()`, an array from the configuration, and a Boolean.

However, the method `add` accepts 3 arguments:
```php
public function add($uri, $redirect = '', $passive = TRUE)
```
Looks like the `TRUE` and `FALSE` flags fit into the `$passive` argument. Meaning the arguments are supplied in incorrect order.

**Comment by daylightstudio** [comment]
The function allows for an array as the first parameter and if so, then it will use the $redirect as the $passive value (see line 89)

**Comment by martynassateika** [comment]
Ahh I see, a bit confusing but not a bug then :-)

The PhpDoc seems a bit wrong though:
```php
* @param string The URI location of the page to remove
```
Should be "... to add" I think.

**Comment by daylightstudio** [comment]
That is indeed incorrect.
