### ISSUE TITLE
Error of Folder writable

### ISSUE THREAD

**Issue by MusahMusah** [daylightstudio/FUEL-CMS#545]
I just started using The Fuel CMS so am new to it, running  my Application on UBUNTU 18.04 and made all the folders in /opt/lamp/htdocs writable but still got this message after i used the fuel cms part to create a page.
error message:
You must make the /opt/lampp/htdocs/e-learning/fuel/application/cache/dwoo/compiled/ folder writable.

**Comment by daylightstudio** [comment]
Are you sure that folder is writable by PHP? What are the permissions on the folder?
