### ISSUE TITLE
Error with MariaDB on Raspberry

### ISSUE THREAD

**Issue by mauriziotallarico** [daylightstudio/FUEL-CMS#550]
Hello, after following all the steps required, i got this error both with "mysql" and "mysqli".
I'm using MariaDB version 10.3.17 

> 
An uncaught Exception was encountered

Type: Error

Message: Call to undefined function mysqli_init()

Filename: /var/www/html/FUEL-CMS/fuel/codeigniter/database/drivers/mysqli/mysqli_driver.php

Line Number: 135

Backtrace:

File: /var/www/html/FUEL-CMS/fuel/modules/fuel/core/Loader.php
Line: 473
Function: DB

File: /var/www/html/FUEL-CMS/fuel/modules/fuel/core/MY_Model.php
Line: 159
Function: database

File: /var/www/html/FUEL-CMS/fuel/modules/fuel/core/MY_Model.php
Line: 112
Function: initialize

File: /var/www/html/FUEL-CMS/fuel/modules/fuel/core/Loader.php
Line: 241
Function: load_class

File: /var/www/html/FUEL-CMS/fuel/modules/fuel/core/Loader.php
Line: 455
Function: model

File: /var/www/html/FUEL-CMS/fuel/modules/fuel/libraries/Fuel_pages.php
Line: 645
Function: module_model

File: /var/www/html/FUEL-CMS/fuel/modules/fuel/libraries/Fuel_pages.php
Line: 558
Function: assign_location

File: /var/www/html/FUEL-CMS/fuel/modules/fuel/libraries/Fuel_pages.php
Line: 525
Function: initialize

File: /var/www/html/FUEL-CMS/fuel/modules/fuel/libraries/Fuel_pages.php
Line: 65
Function: __construct

File: /var/www/html/FUEL-CMS/fuel/modules/fuel/controllers/Page_router.php
Line: 70
Function: create

File: /var/www/html/FUEL-CMS/index.php
Line: 364
Function: require_once

Could you pleas help?
Thanks

**Comment by daylightstudio** [comment]
This looks to be an environment CI issue:
https://stackoverflow.com/questions/33612956/codeigniter-fatal-error-call-to-undefined-function-mysqli-init
