### ISSUE TITLE
getshell in assets

### ISSUE THREAD

**Issue by pxss** [daylightstudio/FUEL-CMS#551]
1.  First create a php file that executes the command and compress the php file into a zip
<img width="606" alt="1" src="https://user-images.githubusercontent.com/9522862/74303980-98127100-4d96-11ea-9b59-101e6d44d889.png">
<img width="320" alt="2" src="https://user-images.githubusercontent.com/9522862/74304008-b11b2200-4d96-11ea-8039-012dfdde450f.png">

2.Upload files in assets and check Unzip zip files
<img width="782" alt="3" src="https://user-images.githubusercontent.com/9522862/74304057-d740c200-4d96-11ea-8759-b96f7c372bd8.png">

3.Click assets to see the uploaded php file
<img width="1647" alt="4" src="https://user-images.githubusercontent.com/9522862/74304105-f4759080-4d96-11ea-8ab0-b4aee5a5f1b0.png">

4.Execute system command
<img width="507" alt="5" src="https://user-images.githubusercontent.com/9522862/74304129-09522400-4d97-11ea-9e57-f4e286c860b5.png">

**Comment by daylightstudio** [comment]
This issue was remedied by removing the zip option altogether.
