### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by liyuange2007** [daylightstudio/FUEL-CMS#557]
I installed as instruction. I did  it many days, but still don't solve it. who can help me?
This is my .htaccess
I use mamp. php7.0.33
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteBase /FUEL-CMS-master/

	<Files .*>
		Order Deny,Allow
		Deny From All
	</Files>

	# Allow asset folders through
	RewriteRule ^(fuel/modules/(.+)?/assets/(.+)) - [L]

	# Protect application and system files from being viewed
	RewriteRule ^(fuel/install/.+|fuel/crons/.+|fuel/data_backup/.+|fuel/codeigniter/.+|fuel/modules/.+|fuel/application/.+) - [F,L]

	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d

	RewriteRule .* index.php/$0 [L]

	# Prevents access to dot files (.git, .htaccess) - security.
	RewriteCond %{SCRIPT_FILENAME} -d
	RewriteCond %{SCRIPT_FILENAME} -f
	RewriteRule "(^|/)\." - [F]

</IfModule>

http://localhost/FUEL-CMS-master/fuel/dashboard
it still show 404 page not found.

I tried to change RewriteRule .* index.php?/$0 [L]. but it still the same problem.
my other website can hide index.php , i think my apache config is ok.

**Comment by daylightstudio** [comment]
A few questions:

1. Are you able to see the homepage (http://localhost/FUEL-CMS-master)?
2. OR, are you seeing the error on the fuel page (http://localhost/FUEL-CMS-master/fuel/)
3. If, Yes for #2, did you set `$config['admin_enabled'] = TRUE;` in the `fuel/application/config/MY_fuel.php`?

**Comment by liyuange2007** [comment]
> A few questions:
> 
> 1. Are you able to see the homepage (http://localhost/FUEL-CMS-master)?
> 2. OR, are you seeing the error on the fuel page (http://localhost/FUEL-CMS-master/fuel/)
> 3. If, Yes for #2, did you set `$config['admin_enabled'] = TRUE;` in the `fuel/application/config/MY_fuel.php`?

1. Yes. I see the welcome page
2. http://localhost/FUEL-CMS-master/fuel/  redirect to http://localhost/FUEL-CMS-master/fuel/dashboard  
![image](https://user-images.githubusercontent.com/38851152/83769708-648f8580-a6aa-11ea-8f3a-b0ed24159807.png)

Thank you

**Comment by daylightstudio** [comment]
So when you login at `http://localhost/FUEL-CMS-master/fuel/login` do you redirect to the dashboard and it's a 404?

If so, try setting the session save path to a writable directory above the web root.
```
$config['sess_save_path'] = NULL;
```

**Comment by daylightstudio** [comment]
I just noticed that you put the `$config['admin_enabled'] = TRUE;` in your `MY_config.php` and not the `MY_fuel.php`.

**Comment by liyuange2007** [comment]
sorry i change the wrong file. Now it works. thank you so much
