### ISSUE TITLE
then i am installed 

### ISSUE THREAD

**Issue by humayunsaleem410** [daylightstudio/FUEL-CMS#558]
![Screenshot (48)](https://user-images.githubusercontent.com/30058423/85003784-1c736700-b170-11ea-86e7-283562171542.png)
![Screenshot (49)](https://user-images.githubusercontent.com/30058423/85003789-1ed5c100-b170-11ea-916e-fb46d6b0842e.png)
![Screenshot (50)](https://user-images.githubusercontent.com/30058423/85003795-2006ee00-b170-11ea-92c4-7f1aa7f64381.png)
import database successfully
username "root"
password""
bd_name: fuel_schema.sql
what is other one issue ?

**Comment by daylightstudio** [comment]
Not sure I follow what your issue is and what error messages you are seeing.

**Comment by humayunsaleem410** [comment]
did you see my screenshot.... then i am going to localhost/FUEL-CMS-master/index.php
this error

**Comment by humayunsaleem410** [comment]
see make folder wrriteable ...........

**Comment by daylightstudio** [comment]
Are you saying that those folders aren't writable?

**Comment by humayunsaleem410** [comment]
yes i say about  folders aren't writable .....................

**Comment by daylightstudio** [comment]
It looks like you are using xampp so try these directions for making the folder writable:
https://superuser.com/questions/172170/make-xampp-program-directory-writeable#:~:text=You%20can%20set%20permissions%20for,allow%20you%20to%20make%20changes.
