### ISSUE TITLE
General users can modify the administrator password  vulnerability

### ISSUE THREAD

**Issue by leerina** [daylightstudio/FUEL-CMS#560]
General users can modify the administrator password and account infomation vulnerability .
for example:
The account test123 can chanage the admin password!!!
step 1:
log in test123:
<img width="958" alt="1" src="https://user-images.githubusercontent.com/12816285/85488214-81abda00-b600-11ea-9b6e-b8c0551322df.png">
Step 2:
edit Any non-administrator account：
<img width="705" alt="2" src="https://user-images.githubusercontent.com/12816285/85488408-d3546480-b600-11ea-9307-ead12b54c763.png">
<img width="662" alt="3" src="https://user-images.githubusercontent.com/12816285/85488485-f41cba00-b600-11ea-838d-f1251856ee96.png">
Step 3:
Save the chanage:
<img width="641" alt="4" src="https://user-images.githubusercontent.com/12816285/85488606-2d552a00-b601-11ea-855a-cf82d5189bf4.png">
Then Intercept the packets and chanage the "id" and "__fuel_id__" value 1
<img width="492" alt="5" src="https://user-images.githubusercontent.com/12816285/85489127-211d9c80-b602-11ea-9b18-0adaf8ece8b5.png">
<img width="516" alt="6" src="https://user-images.githubusercontent.com/12816285/85489142-2549ba00-b602-11ea-86ea-fb0bc4edf57e.png">
Success :
<img width="705" alt="7" src="https://user-images.githubusercontent.com/12816285/85489184-35619980-b602-11ea-97a9-a6bf6e3c1240.png">
Step 4:
log in admin use new password ：
<img width="942" alt="8" src="https://user-images.githubusercontent.com/12816285/85489385-7f4a7f80-b602-11ea-9fb1-158792134c72.png">
<img width="859" alt="9" src="https://user-images.githubusercontent.com/12816285/85489564-c33d8480-b602-11ea-83a7-9e945286141c.png">
<img width="947" alt="10" src="https://user-images.githubusercontent.com/12816285/85489667-e9fbbb00-b602-11ea-8537-ac7baadf6299.png">

**Comment by daylightstudio** [comment]
Thanks for the submission and example. Can you verify this latest fix on your end?
