### ISSUE TITLE
Forum password reminder

### ISSUE THREAD

**Issue by martynassateika** [daylightstudio/FUEL-CMS#565]
Tried resetting my forum password yesterday, first entering the username, then the email, but didn't receive anything. Is it not working? I don't think I deleted my account.

**Comment by daylightstudio** [comment]
Could you provide your unsername/email (maybe directly) that you used for the forum? Also, did you check your SPAM folder by chance?

**Comment by martynassateika** [comment]
Nothing in the spam folder! I've just sent you an e-mail.

**Comment by daylightstudio** [comment]
I've updated the SMTP settings to see if that helps. Can you give it a go and report back your experience?

**Comment by martynassateika** [comment]
Thank you! The form now worked and I was able to log in.

**Comment by daylightstudio** [comment]
Thanks for letting us know. It was probably like that for a while.
