### ISSUE TITLE
forum.getfuelcms.com email support not working

### ISSUE THREAD

**Issue by claudiunv** [daylightstudio/FUEL-CMS#585]
Hi, the forum is still active?

I have an account from 2012, but I lost the password and I can't get an email to reset it.
Then I created a new account, but now I have "You need to confirm your email address. Click here to resend the confirmation email." on the forum's page, with no success to activate the new account.

Is there any way to fix this?

Thanks

**Comment by daylightstudio** [comment]
Does this mean you aren't receiving the confirmation email (check SPAM folder just in case).

**Comment by claudiunv** [comment]
Thank you for responding me :smile: 

Verified, nothing from forum's email:

> in:spam fuelcms 
> 
> No messages matched your search. Try using search options such as sender, date, size and more.

**Comment by daylightstudio** [comment]
Can you send me the signup email address you used to the email address found here?
https://forum.getfuelcms.com/profile/admin

We are on a free account for sending emails and it may have gotten full... spam is crazy.

**Comment by claudiunv** [comment]
Thank you, issue solved.
