### ISSUE TITLE
Is encryption_key used in any way in Fuel_assets::upload method?

### ISSUE THREAD

**Issue by ferran-romero** [daylightstudio/FUEL-CMS#592]
Hello,

I'm not sure if this is a bug or there's something missing in the current fuel implementation, but I realized that in the upload method of modules/fuel/libraries/Fuel_assets.php you're adding an error if there isn't encryption_key in the settings.

```php	
      public function upload($params = array())
      {
		$this->CI->load->library('upload');
		$this->CI->load->library('image_lib');
		$this->CI->load->library('encryption');

		if (!config_item('encryption_key'))
		{
			$this->_add_error(lang('assets_encryption_key_missing'));
		}
              // More stuff
      }
```

However, this doesn't seem to be used in the method itself, and arguably doesn't make sense if you don't plan on using an encryption key (which seems intended solely for use by the Encrypt / Encryption library).

Best regards.

**Comment by daylightstudio** [comment]
FUEL needs the encryption key config value to be set for file uploads.

**Comment by ferran-romero** [comment]
Ok, but just for learning, where the encryption key is used in the Fuel_assets library? I was trying to find it, but I couldn't see it. Thanks anyway.
