### ISSUE TITLE
FUEL CMS 1.5.2 allows SQL Injection via parameter 'id' in fuel/modules/fuel/controllers/Blocks.php

### ISSUE THREAD

**Issue by bcvgh** [daylightstudio/FUEL-CMS#604]
login required.

fuel/modules/fuel/controllers/Blocks.php

line 64 import_view method starts

Line 70 receives the id parameter of the post request and enters the import method

![image](https://github.com/daylightstudio/FUEL-CMS/assets/56790427/beda0025-4ba5-4d04-9ad3-f9b5712fdcc3)

fuel/modules/fuel/libraries/Fuel_blocks.php

Then enter the find_by_key method on line 307

![image](https://github.com/daylightstudio/FUEL-CMS/assets/56790427/5e44353a-f961-4405-9e86-75dab1e4910c)

Because the find_by_key method does not exist, enter the __call method of the current object

Enter line 4421 of MY_Model.php, pass parameters to $this->db->where() method

![image](https://github.com/daylightstudio/FUEL-CMS/assets/56790427/ceaa225d-620e-458c-8c07-3ebe6e100e1c)

At this time, the external input string is spliced into the SQL statement through the $this->db->where() method, But at this time, the external input will be surrounded by single quotes because of codeigniter's safe processing of the where method, so the injection has not yet been caused..

![image](https://github.com/daylightstudio/FUEL-CMS/assets/56790427/3e917d76-30fa-4f4d-89e0-14180ee443c3)

Until line 4450, the user's external input is stored in the $other_args array at this time, and has not been processed safely

![image](https://user-images.githubusercontent.com/56790427/237115647-840de685-5b5d-47ed-ade6-b44ca1dd5beb.png)

Enter the $this->db->order_by() method, at this time the external input is spliced into the sql statement again, and there is no single quotation mark included

![image](https://github.com/daylightstudio/FUEL-CMS/assets/56790427/beef05cb-9a97-4a09-b956-f9cdc0b47dde)

Finally, the $this->db->get() method executes the database command, causing sql injection

![image](https://user-images.githubusercontent.com/56790427/237115932-12f850ef-0e88-4421-9f78-6d56c1dd652a.png)

![image](https://github.com/daylightstudio/FUEL-CMS/assets/56790427/18acc028-9d38-48df-90d3-ab30a9af1032)

sqlmap:

![image](https://github.com/daylightstudio/FUEL-CMS/assets/56790427/5003900b-dd66-45c1-9407-ce3a17a3d65b)

**Comment by daylightstudio** [comment]
Thank you for the detailed report @bcvgh. I've pushed a fix for that issue which I believe was caused by the `find_by_name` method call (`find_by_key` method does exist).

**Comment by bcvgh** [comment]
Yes, my expression was incorrect. What I want to say is that there is a vulnerability in the find_by_name method
